// 名称: 全球国家信息查询
// 描述: 提供全球国家和地区的详细信息，包括代码、区号、时区、外贸相关信息等
// 路径: seedtool/lib/tools/global-country-info.ts
// 作者: Jensfrank
// 更新时间: 2025-07-28

export interface CountryInfo {
  // 基础信息
  name_cn: string;
  name_en: string;
  iso2: string;
  iso3: string;
  capital_cn: string;
  capital_en: string;
  continent_cn: string;
  continent_en: string;
  
  // 通讯信息
  dial_code: string;
  tld: string;
  timezone: string;
  
  // 文化信息
  currency_code: string;
  currency_name_cn: string;
  currency_symbol: string;
  language_cn: string[];
  language_en: string[];
  religion: string[];
  
  // 地理信息
  area_km2: number;
  population: number;
  
  // 外贸相关
  major_ports?: string[];
  business_hours?: string;
  business_etiquette?: string[];
  major_holidays?: string[];
  trade_notes?: string[];
  
  // 其他
  driving_side: 'left' | 'right';
  power_plug: string;
  voltage: string;
}

// 精简版数据用于测试
export const COUNTRY_DATA: CountryInfo[] = [
  { 
//亚洲国家
    name_cn: "中国", 
    name_en: "China", 
    iso2: "CN", 
    iso3: "CHN", 
    dial_code: "+86", 
    capital_cn: "北京", 
    capital_en: "Beijing", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".cn", 
    timezone: "Asia/Shanghai", 
    currency_code: "CNY", 
    currency_name_cn: "人民币",
    currency_symbol: "¥",
    language_cn: ["汉语", "普通话"],
    language_en: ["Chinese", "Mandarin"],
    religion: ["无宗教", "佛教", "道教", "基督教"],
    area_km2: 9596961,
    population: 1411000000,
    major_ports: ["上海港", "宁波舟山港", "深圳港", "广州港", "青岛港", "天津港", "大连港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "交换名片时双手递接",
      "初次见面握手即可",
      "避免谈论政治敏感话题",
      "商务宴请是建立关系的重要方式"
    ],
    major_holidays: ["春节(1-2月)", "清明节(4月)", "劳动节(5月1日)", "端午节(5-6月)", "中秋节(9-10月)", "国庆节(10月1-7日)"],
    trade_notes: [
      "注重建立长期合作关系",
      "重视面子和人情",
      "决策过程可能较长",
      "合同细节需要仔细确认"
    ],
    driving_side: "right",
    power_plug: "A/C/I",
    voltage: "220V"
  },
    { 
    name_cn: "日本", 
    name_en: "Japan", 
    iso2: "JP", 
    iso3: "JPN", 
    dial_code: "+81", 
    capital_cn: "东京", 
    capital_en: "Tokyo", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".jp", 
    timezone: "Asia/Tokyo", 
    currency_code: "JPY", 
    currency_name_cn: "日元",
    currency_symbol: "¥",
    language_cn: ["日语"],
    language_en: ["Japanese"],
    religion: ["神道教", "佛教", "无宗教"],
    area_km2: 377975,
    population: 125800000,
    major_ports: ["东京港", "横滨港", "名古屋港", "大阪港", "神户港", "千叶港"],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "交换名片(名刺)极其重要，双手递接",
      "鞠躬是基本礼仪",
      "避免直接说'不'",
      "重视集体决策",
      "守时是基本要求"
    ],
    major_holidays: ["新年(1月1-3日)", "黄金周(4月末-5月初)", "盂兰盆节(8月中旬)", "体育节(10月第2个周一)"],
    trade_notes: [
      "注重细节和品质",
      "决策过程较慢但执行彻底",
      "重视长期合作关系",
      "偏好面对面会议"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "100V"
  },
    { 
    name_cn: "韩国", 
    name_en: "South Korea", 
    iso2: "KR", 
    iso3: "KOR", 
    dial_code: "+82", 
    capital_cn: "首尔", 
    capital_en: "Seoul", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".kr", 
    timezone: "Asia/Seoul", 
    currency_code: "KRW", 
    currency_name_cn: "韩元",
    currency_symbol: "₩",
    language_cn: ["韩语"],
    language_en: ["Korean"],
    religion: ["无宗教", "基督教", "佛教"],
    area_km2: 100210,
    population: 51700000,
    major_ports: ["釜山港", "仁川港", "光阳港", "蔚山港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "重视年龄和地位",
      "交换名片用双手",
      "避免直接拒绝",
      "聚餐文化重要"
    ],
    major_holidays: ["新年(1月1日)", "春节(1-2月)", "儿童节(5月5日)", "光复节(8月15日)", "中秋节(9-10月)"],
    trade_notes: [
      "决策速度快",
      "重视人际关系",
      "加班文化普遍",
      "等级观念较强"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "印度", 
    name_en: "India", 
    iso2: "IN", 
    iso3: "IND", 
    dial_code: "+91", 
    capital_cn: "新德里", 
    capital_en: "New Delhi", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".in", 
    timezone: "Asia/Kolkata", 
    currency_code: "INR", 
    currency_name_cn: "印度卢比",
    currency_symbol: "₹",
    language_cn: ["印地语", "英语"],
    language_en: ["Hindi", "English"],
    religion: ["印度教", "伊斯兰教", "基督教", "锡克教"],
    area_km2: 3287263,
    population: 1380000000,
    major_ports: ["孟买港", "金奈港", "加尔各答港", "科钦港"],
    business_hours: "周一至周六 10:00-18:00",
    business_etiquette: [
      "避免用左手",
      "注意素食者较多",
      "家庭和关系重要",
      "时间观念较灵活"
    ],
    major_holidays: ["共和国日(1月26日)", "洒红节(3月)", "排灯节(10-11月)", "独立日(8月15日)"],
    trade_notes: [
      "谈判可能需要耐心",
      "重视个人关系",
      "等级制度明显",
      "英语广泛使用"
    ],
    driving_side: "left",
    power_plug: "C/D/M",
    voltage: "230V"
  },
  { 
    name_cn: "新加坡", 
    name_en: "Singapore", 
    iso2: "SG", 
    iso3: "SGP", 
    dial_code: "+65", 
    capital_cn: "新加坡", 
    capital_en: "Singapore", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".sg", 
    timezone: "Asia/Singapore", 
    currency_code: "SGD", 
    currency_name_cn: "新加坡元",
    currency_symbol: "S$",
    language_cn: ["英语", "中文", "马来语", "泰米尔语"],
    language_en: ["English", "Chinese", "Malay", "Tamil"],
    religion: ["佛教", "基督教", "伊斯兰教", "道教", "印度教"],
    area_km2: 728,
    population: 5450000,
    major_ports: ["新加坡港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "准时非常重要",
      "尊重多元文化",
      "名片交换重要",
      "着装正式"
    ],
    major_holidays: ["新年(1月1日)", "春节(1-2月)", "开斋节", "屠妖节", "圣诞节(12月25日)"],
    trade_notes: [
      "效率极高",
      "法治严明",
      "英语为商务语言",
      "亚洲商务枢纽"
    ],
    driving_side: "left",
    power_plug: "G",
    voltage: "230V"
  },
  { 
    name_cn: "泰国", 
    name_en: "Thailand", 
    iso2: "TH", 
    iso3: "THA", 
    dial_code: "+66", 
    capital_cn: "曼谷", 
    capital_en: "Bangkok", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".th", 
    timezone: "Asia/Bangkok", 
    currency_code: "THB", 
    currency_name_cn: "泰铢",
    currency_symbol: "฿",
    language_cn: ["泰语"],
    language_en: ["Thai"],
    religion: ["佛教", "伊斯兰教"],
    area_km2: 513120,
    population: 69800000,
    major_ports: ["曼谷港", "林查班港"],
    business_hours: "周一至周五 8:30-17:30",
    business_etiquette: [
      "避免触碰头部",
      "尊重王室",
      "保持微笑",
      "避免当众批评"
    ],
    major_holidays: ["新年(1月1日)", "万佛节(2月)", "宋干节(4月13-15日)", "国王生日(7月28日)"],
    trade_notes: [
      "重视面子",
      "避免冲突",
      "等级观念存在",
      "礼物文化重要"
    ],
    driving_side: "left",
    power_plug: "A/B/C",
    voltage: "230V"
  },
  { 
    name_cn: "马来西亚", 
    name_en: "Malaysia", 
    iso2: "MY", 
    iso3: "MYS", 
    dial_code: "+60", 
    capital_cn: "吉隆坡", 
    capital_en: "Kuala Lumpur", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".my", 
    timezone: "Asia/Kuala_Lumpur", 
    currency_code: "MYR", 
    currency_name_cn: "马来西亚林吉特",
    currency_symbol: "RM",
    language_cn: ["马来语", "英语", "中文"],
    language_en: ["Malay", "English", "Chinese"],
    religion: ["伊斯兰教", "佛教", "基督教", "印度教"],
    area_km2: 330803,
    population: 32400000,
    major_ports: ["巴生港", "槟城港", "柔佛港"],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "尊重多元文化",
      "避免左手",
      "注意宗教差异",
      "保持礼貌"
    ],
    major_holidays: ["新年(1月1日)", "春节(1-2月)", "开斋节", "屠妖节", "圣诞节(12月25日)"],
    trade_notes: [
      "英语广泛使用",
      "关系网重要",
      "决策较慢",
      "注意种族敏感"
    ],
    driving_side: "left",
    power_plug: "G",
    voltage: "240V"
  },
  { 
    name_cn: "印度尼西亚", 
    name_en: "Indonesia", 
    iso2: "ID", 
    iso3: "IDN", 
    dial_code: "+62", 
    capital_cn: "雅加达", 
    capital_en: "Jakarta", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".id", 
    timezone: "Asia/Jakarta", 
    currency_code: "IDR", 
    currency_name_cn: "印尼盾",
    currency_symbol: "Rp",
    language_cn: ["印尼语"],
    language_en: ["Indonesian"],
    religion: ["伊斯兰教", "基督教", "印度教", "佛教"],
    area_km2: 1904569,
    population: 273500000,
    major_ports: ["丹戎不碌港", "泗水港", "三宝垄港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "避免左手",
      "尊重等级",
      "耐心重要",
      "避免直接冲突"
    ],
    major_holidays: ["新年(1月1日)", "开斋节", "宰牲节", "独立日(8月17日)"],
    trade_notes: [
      "关系优先",
      "决策缓慢",
      "避免施压",
      "注意宗教习俗"
    ],
    driving_side: "left",
    power_plug: "C/F",
    voltage: "230V"
  },
  { 
    name_cn: "菲律宾", 
    name_en: "Philippines", 
    iso2: "PH", 
    iso3: "PHL", 
    dial_code: "+63", 
    capital_cn: "马尼拉", 
    capital_en: "Manila", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".ph", 
    timezone: "Asia/Manila", 
    currency_code: "PHP", 
    currency_name_cn: "菲律宾比索",
    currency_symbol: "₱",
    language_cn: ["菲律宾语", "英语"],
    language_en: ["Filipino", "English"],
    religion: ["天主教", "基督教", "伊斯兰教"],
    area_km2: 300000,
    population: 109600000,
    major_ports: ["马尼拉港", "苏比克港", "宿务港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "重视人际关系",
      "避免当众批评",
      "时间观念灵活",
      "尊重年长者"
    ],
    major_holidays: ["新年(1月1日)", "圣周(3-4月)", "独立日(6月12日)", "圣诞节(12月25日)"],
    trade_notes: [
      "英语优势",
      "关系网重要",
      "避免冲突",
      "家庭价值观强"
    ],
    driving_side: "right",
    power_plug: "A/B/C",
    voltage: "220V"
  },
  { 
    name_cn: "越南", 
    name_en: "Vietnam", 
    iso2: "VN", 
    iso3: "VNM", 
    dial_code: "+84", 
    capital_cn: "河内", 
    capital_en: "Hanoi", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".vn", 
    timezone: "Asia/Ho_Chi_Minh", 
    currency_code: "VND", 
    currency_name_cn: "越南盾",
    currency_symbol: "₫",
    language_cn: ["越南语"],
    language_en: ["Vietnamese"],
    religion: ["无宗教", "佛教", "天主教"],
    area_km2: 331212,
    population: 97300000,
    major_ports: ["西贡港", "海防港", "岘港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "尊重年长者",
      "名片双手递接",
      "避免过度直接",
      "建立关系重要"
    ],
    major_holidays: ["新年(1月1日)", "春节(1-2月)", "雄王节(农历3月10日)", "国庆日(9月2日)"],
    trade_notes: [
      "关系网络关键",
      "耐心很重要",
      "等级制度明显",
      "礼物交换常见"
    ],
    driving_side: "right",
    power_plug: "A/C/D",
    voltage: "220V"
  },
  { 
    name_cn: "阿联酋", 
    name_en: "United Arab Emirates", 
    iso2: "AE", 
    iso3: "ARE", 
    dial_code: "+971", 
    capital_cn: "阿布扎比", 
    capital_en: "Abu Dhabi", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".ae", 
    timezone: "Asia/Dubai", 
    currency_code: "AED", 
    currency_name_cn: "阿联酋迪拉姆",
    currency_symbol: "د.إ",
    language_cn: ["阿拉伯语", "英语"],
    language_en: ["Arabic", "English"],
    religion: ["伊斯兰教"],
    area_km2: 83600,
    population: 9890000,
    major_ports: ["迪拜港", "阿布扎比港", "沙迦港"],
    business_hours: "周日至周四 8:00-17:00",
    business_etiquette: [
      "避免左手",
      "尊重伊斯兰文化",
      "建立信任重要",
      "避免直接拒绝"
    ],
    major_holidays: ["新年(1月1日)", "开斋节", "宰牲节", "国庆日(12月2日)"],
    trade_notes: [
      "周五周六是周末",
      "斋月期间特殊",
      "重视个人关系",
      "决策可能缓慢"
    ],
    driving_side: "right",
    power_plug: "G",
    voltage: "230V"
  },
  { 
    name_cn: "沙特阿拉伯", 
    name_en: "Saudi Arabia", 
    iso2: "SA", 
    iso3: "SAU", 
    dial_code: "+966", 
    capital_cn: "利雅得", 
    capital_en: "Riyadh", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".sa", 
    timezone: "Asia/Riyadh", 
    currency_code: "SAR", 
    currency_name_cn: "沙特里亚尔",
    currency_symbol: "﷼",
    language_cn: ["阿拉伯语"],
    language_en: ["Arabic"],
    religion: ["伊斯兰教"],
    area_km2: 2149690,
    population: 34800000,
    major_ports: ["吉达港", "达曼港", "朱拜勒港"],
    business_hours: "周日至周四 8:00-15:00",
    business_etiquette: [
      "严格遵守伊斯兰教规",
      "男女商务分开",
      "避免左手",
      "耐心和尊重"
    ],
    major_holidays: ["开斋节", "宰牲节", "国庆日(9月23日)"],
    trade_notes: [
      "周五周六周末",
      "斋月特殊安排",
      "决策较慢",
      "个人关系关键"
    ],
    driving_side: "right",
    power_plug: "G",
    voltage: "230V"
  },
  { 
    name_cn: "土耳其", 
    name_en: "Turkey", 
    iso2: "TR", 
    iso3: "TUR", 
    dial_code: "+90", 
    capital_cn: "安卡拉", 
    capital_en: "Ankara", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".tr", 
    timezone: "Europe/Istanbul", 
    currency_code: "TRY", 
    currency_name_cn: "土耳其里拉",
    currency_symbol: "₺",
    language_cn: ["土耳其语"],
    language_en: ["Turkish"],
    religion: ["伊斯兰教"],
    area_km2: 783562,
    population: 84300000,
    major_ports: ["伊斯坦布尔港", "伊兹密尔港", "梅尔辛港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "建立个人关系",
      "茶文化重要",
      "避免左手",
      "尊重长者"
    ],
    major_holidays: ["新年(1月1日)", "国家主权日(4月23日)", "开斋节", "共和国日(10月29日)"],
    trade_notes: [
      "关系导向",
      "谈判需耐心",
      "等级制度存在",
      "好客文化"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "230V"
  },
  { 
    name_cn: "以色列", 
    name_en: "Israel", 
    iso2: "IL", 
    iso3: "ISR", 
    dial_code: "+972", 
    capital_cn: "耶路撒冷", 
    capital_en: "Jerusalem", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".il", 
    timezone: "Asia/Jerusalem", 
    currency_code: "ILS", 
    currency_name_cn: "以色列谢克尔",
    currency_symbol: "₪",
    language_cn: ["希伯来语", "阿拉伯语"],
    language_en: ["Hebrew", "Arabic"],
    religion: ["犹太教", "伊斯兰教", "基督教"],
    area_km2: 20770,
    population: 9300000,
    major_ports: ["海法港", "阿什杜德港"],
    business_hours: "周日至周四 8:00-17:00",
    business_etiquette: [
      "直接坦率",
      "非正式风格",
      "创新思维",
      "注意宗教差异"
    ],
    major_holidays: ["犹太新年(9-10月)", "赎罪日(9-10月)", "逾越节(3-4月)", "独立日(4-5月)"],
    trade_notes: [
      "周五周六安息日",
      "高科技发达",
      "英语普及",
      "安全考虑重要"
    ],
    driving_side: "right",
    power_plug: "C/H",
    voltage: "230V"
  },
  { 
    name_cn: "巴基斯坦", 
    name_en: "Pakistan", 
    iso2: "PK", 
    iso3: "PAK", 
    dial_code: "+92", 
    capital_cn: "伊斯兰堡", 
    capital_en: "Islamabad", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".pk", 
    timezone: "Asia/Karachi", 
    currency_code: "PKR", 
    currency_name_cn: "巴基斯坦卢比",
    currency_symbol: "₨",
    language_cn: ["乌尔都语", "英语"],
    language_en: ["Urdu", "English"],
    religion: ["伊斯兰教"],
    area_km2: 881913,
    population: 220900000,
    major_ports: ["卡拉奇港", "卡西姆港", "瓜达尔港"],
    business_hours: "周一至周五 9:00-17:00, 周六 9:00-13:00",
    business_etiquette: [
      "避免左手",
      "尊重伊斯兰习俗",
      "建立信任重要",
      "男女交往谨慎"
    ],
    major_holidays: ["新年(1月1日)", "巴基斯坦日(3月23日)", "独立日(8月14日)", "开斋节", "宰牲节"],
    trade_notes: [
      "关系网络关键",
      "决策层级多",
      "斋月特殊安排",
      "英语商务通用"
    ],
    driving_side: "left",
    power_plug: "C/D",
    voltage: "230V"
  },
  { 
    name_cn: "孟加拉国", 
    name_en: "Bangladesh", 
    iso2: "BD", 
    iso3: "BGD", 
    dial_code: "+880", 
    capital_cn: "达卡", 
    capital_en: "Dhaka", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".bd", 
    timezone: "Asia/Dhaka", 
    currency_code: "BDT", 
    currency_name_cn: "孟加拉塔卡",
    currency_symbol: "৳",
    language_cn: ["孟加拉语"],
    language_en: ["Bengali"],
    religion: ["伊斯兰教", "印度教"],
    area_km2: 147570,
    population: 164700000,
    major_ports: ["吉大港", "蒙格拉港"],
    business_hours: "周日至周四 9:00-17:00",
    business_etiquette: [
      "尊重年长者",
      "避免左手",
      "建立关系重要",
      "耐心必要"
    ],
    major_holidays: ["新年(1月1日)", "独立日(3月26日)", "孟加拉新年(4月14日)", "开斋节", "杜尔加女神节"],
    trade_notes: [
      "纺织业发达",
      "等级制度明显",
      "决策缓慢",
      "个人关系优先"
    ],
    driving_side: "left",
    power_plug: "C/D/G/K",
    voltage: "220V"
  },
  { 
    name_cn: "斯里兰卡", 
    name_en: "Sri Lanka", 
    iso2: "LK", 
    iso3: "LKA", 
    dial_code: "+94", 
    capital_cn: "科伦坡", 
    capital_en: "Colombo", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".lk", 
    timezone: "Asia/Colombo", 
    currency_code: "LKR", 
    currency_name_cn: "斯里兰卡卢比",
    currency_symbol: "Rs",
    language_cn: ["僧伽罗语", "泰米尔语"],
    language_en: ["Sinhala", "Tamil"],
    religion: ["佛教", "印度教", "伊斯兰教", "基督教"],
    area_km2: 65610,
    population: 21900000,
    major_ports: ["科伦坡港", "汉班托塔港"],
    business_hours: "周一至周五 8:30-17:00",
    business_etiquette: [
      "尊重等级",
      "避免用左手",
      "保守着装",
      "建立关系重要"
    ],
    major_holidays: ["新年(1月1日)", "独立日(2月4日)", "泰米尔新年(4月)", "卫塞节(5月)", "圣诞节(12月25日)"],
    trade_notes: [
      "茶叶出口大国",
      "英语广泛使用",
      "官僚程序多",
      "时间观念灵活"
    ],
    driving_side: "left",
    power_plug: "D/G",
    voltage: "230V"
  },
  { 
    name_cn: "尼泊尔", 
    name_en: "Nepal", 
    iso2: "NP", 
    iso3: "NPL", 
    dial_code: "+977", 
    capital_cn: "加德满都", 
    capital_en: "Kathmandu", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".np", 
    timezone: "Asia/Kathmandu", 
    currency_code: "NPR", 
    currency_name_cn: "尼泊尔卢比",
    currency_symbol: "₨",
    language_cn: ["尼泊尔语"],
    language_en: ["Nepali"],
    religion: ["印度教", "佛教"],
    area_km2: 147516,
    population: 29100000,
    major_ports: [],
    business_hours: "周日至周五 10:00-17:00",
    business_etiquette: [
      "双手合十问候",
      "尊重宗教习俗",
      "避免用左手",
      "保守着装"
    ],
    major_holidays: ["新年(1月1日)", "共和国日(5月29日)", "宪法日(9月20日)", "德赛节(10月)"],
    trade_notes: [
      "内陆国家依赖印度",
      "基础设施薄弱",
      "官僚程序复杂",
      "现金交易为主"
    ],
    driving_side: "left",
    power_plug: "C/D/M",
    voltage: "230V"
  },
  { 
    name_cn: "不丹", 
    name_en: "Bhutan", 
    iso2: "BT", 
    iso3: "BTN", 
    dial_code: "+975", 
    capital_cn: "廷布", 
    capital_en: "Thimphu", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".bt", 
    timezone: "Asia/Thimphu", 
    currency_code: "BTN", 
    currency_name_cn: "不丹努尔特鲁姆",
    currency_symbol: "Nu.",
    language_cn: ["宗卡语"],
    language_en: ["Dzongkha"],
    religion: ["佛教", "印度教"],
    area_km2: 38394,
    population: 771600,
    major_ports: [],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "重视环保和幸福",
      "尊重佛教传统",
      "正式场合穿传统服装",
      "避免吸烟"
    ],
    major_holidays: ["国王生日(2月21-23日)", "不丹新年(2-3月)", "国庆日(12月17日)"],
    trade_notes: [
      "重视国民幸福总值",
      "旅游业受限制",
      "水电出口重要",
      "与印度关系密切"
    ],
    driving_side: "left",
    power_plug: "C/D/F/G",
    voltage: "230V"
  },
  { 
    name_cn: "缅甸", 
    name_en: "Myanmar", 
    iso2: "MM", 
    iso3: "MMR", 
    dial_code: "+95", 
    capital_cn: "内比都", 
    capital_en: "Naypyidaw", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".mm", 
    timezone: "Asia/Yangon", 
    currency_code: "MMK", 
    currency_name_cn: "缅甸元",
    currency_symbol: "K",
    language_cn: ["缅甸语"],
    language_en: ["Burmese"],
    religion: ["佛教", "基督教", "伊斯兰教"],
    area_km2: 676578,
    population: 54400000,
    major_ports: ["仰光港", "毛淡棉港"],
    business_hours: "周一至周五 9:30-16:30",
    business_etiquette: [
      "尊重佛教传统",
      "避免触碰头部",
      "脱鞋进入某些场所",
      "保持礼貌谦逊"
    ],
    major_holidays: ["新年(1月1日)", "独立日(1月4日)", "泼水节(4月)", "烈士节(7月19日)"],
    trade_notes: [
      "政治环境复杂",
      "基础设施发展中",
      "现金交易普遍",
      "关系网络重要"
    ],
    driving_side: "right",
    power_plug: "C/D/F/G",
    voltage: "230V"
  },
  { 
    name_cn: "老挝", 
    name_en: "Laos", 
    iso2: "LA", 
    iso3: "LAO", 
    dial_code: "+856", 
    capital_cn: "万象", 
    capital_en: "Vientiane", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".la", 
    timezone: "Asia/Vientiane", 
    currency_code: "LAK", 
    currency_name_cn: "老挝基普",
    currency_symbol: "₭",
    language_cn: ["老挝语"],
    language_en: ["Lao"],
    religion: ["佛教"],
    area_km2: 236800,
    population: 7270000,
    major_ports: [],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "双手合十问候",
      "尊重佛教传统",
      "避免公开批评",
      "保持冷静耐心"
    ],
    major_holidays: ["新年(1月1日)", "老挝新年(4月13-15日)", "国庆日(12月2日)"],
    trade_notes: [
      "内陆国家",
      "基础设施有限",
      "与中国贸易增长",
      "决策过程缓慢"
    ],
    driving_side: "right",
    power_plug: "A/B/C/E/F",
    voltage: "230V"
  },
  { 
    name_cn: "柬埔寨", 
    name_en: "Cambodia", 
    iso2: "KH", 
    iso3: "KHM", 
    dial_code: "+855", 
    capital_cn: "金边", 
    capital_en: "Phnom Penh", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".kh", 
    timezone: "Asia/Phnom_Penh", 
    currency_code: "KHR", 
    currency_name_cn: "柬埔寨瑞尔",
    currency_symbol: "៛",
    language_cn: ["高棉语"],
    language_en: ["Khmer"],
    religion: ["佛教"],
    area_km2: 181035,
    population: 16700000,
    major_ports: ["西哈努克港", "金边港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "双手合十问候",
      "尊重年长者",
      "避免触碰头部",
      "保持微笑"
    ],
    major_holidays: ["新年(1月1日)", "高棉新年(4月13-15日)", "独立日(11月9日)", "水节(11月)"],
    trade_notes: [
      "美元广泛使用",
      "纺织业重要",
      "基础设施改善中",
      "与中国关系密切"
    ],
    driving_side: "right",
    power_plug: "A/C/G",
    voltage: "230V"
  },
  { 
    name_cn: "文莱", 
    name_en: "Brunei", 
    iso2: "BN", 
    iso3: "BRN", 
    dial_code: "+673", 
    capital_cn: "斯里巴加湾市", 
    capital_en: "Bandar Seri Begawan", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".bn", 
    timezone: "Asia/Brunei", 
    currency_code: "BND", 
    currency_name_cn: "文莱元",
    currency_symbol: "$",
    language_cn: ["马来语"],
    language_en: ["Malay"],
    religion: ["伊斯兰教"],
    area_km2: 5765,
    population: 437500,
    major_ports: ["摩拉港"],
    business_hours: "周一至周四、周六 8:00-17:00",
    business_etiquette: [
      "严格遵守伊斯兰教规",
      "避免用左手",
      "正式着装",
      "尊重苏丹"
    ],
    major_holidays: ["新年(1月1日)", "国庆日(2月23日)", "苏丹生日(7月15日)", "开斋节"],
    trade_notes: [
      "石油天然气经济",
      "禁酒令严格",
      "周五祈祷时间",
      "政府主导经济"
    ],
    driving_side: "left",
    power_plug: "G",
    voltage: "240V"
  },
  { 
    name_cn: "东帝汶", 
    name_en: "Timor-Leste", 
    iso2: "TL", 
    iso3: "TLS", 
    dial_code: "+670", 
    capital_cn: "帝力", 
    capital_en: "Dili", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".tl", 
    timezone: "Asia/Dili", 
    currency_code: "USD", 
    currency_name_cn: "美元",
    currency_symbol: "$",
    language_cn: ["德顿语", "葡萄牙语"],
    language_en: ["Tetum", "Portuguese"],
    religion: ["天主教"],
    area_km2: 14874,
    population: 1318000,
    major_ports: ["帝力港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "握手问候",
      "尊重天主教传统",
      "时间观念灵活",
      "葡语有优势"
    ],
    major_holidays: ["新年(1月1日)", "独立恢复日(5月20日)", "独立公投日(8月30日)", "圣诞节(12月25日)"],
    trade_notes: [
      "石油依赖经济",
      "基础设施薄弱",
      "美元为官方货币",
      "发展潜力大"
    ],
    driving_side: "left",
    power_plug: "C/E/F/I",
    voltage: "220V"
  },
  { 
    name_cn: "马尔代夫", 
    name_en: "Maldives", 
    iso2: "MV", 
    iso3: "MDV", 
    dial_code: "+960", 
    capital_cn: "马累", 
    capital_en: "Malé", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".mv", 
    timezone: "Indian/Maldives", 
    currency_code: "MVR", 
    currency_name_cn: "马尔代夫拉菲亚",
    currency_symbol: "Rf",
    language_cn: ["迪维希语"],
    language_en: ["Dhivehi"],
    religion: ["伊斯兰教"],
    area_km2: 298,
    population: 540500,
    major_ports: ["马累港"],
    business_hours: "周日至周四 8:00-16:00",
    business_etiquette: [
      "严格遵守伊斯兰教规",
      "禁酒",
      "保守着装",
      "避免公开亲密行为"
    ],
    major_holidays: ["新年(1月1日)", "独立日(7月26日)", "共和国日(11月11日)", "开斋节"],
    trade_notes: [
      "旅游业为主",
      "进口依赖严重",
      "环保要求高",
      "岛屿物流复杂"
    ],
    driving_side: "left",
    power_plug: "C/D/G/J/K/L",
    voltage: "230V"
  },
  { 
    name_cn: "哈萨克斯坦", 
    name_en: "Kazakhstan", 
    iso2: "KZ", 
    iso3: "KAZ", 
    dial_code: "+7", 
    capital_cn: "阿斯塔纳", 
    capital_en: "Astana", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".kz", 
    timezone: "Asia/Almaty", 
    currency_code: "KZT", 
    currency_name_cn: "哈萨克斯坦坚戈",
    currency_symbol: "₸",
    language_cn: ["哈萨克语", "俄语"],
    language_en: ["Kazakh", "Russian"],
    religion: ["伊斯兰教", "基督教"],
    area_km2: 2724900,
    population: 18800000,
    major_ports: ["阿克套港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "握手问候",
      "重视年龄和地位",
      "款待文化重要",
      "耐心和尊重"
    ],
    major_holidays: ["新年(1月1日)", "独立日(12月16日)", "纳吾肉孜节(3月21日)"],
    trade_notes: [
      "石油资源丰富",
      "俄语商务通用",
      "关系网络重要",
      "官僚程序存在"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "乌兹别克斯坦", 
    name_en: "Uzbekistan", 
    iso2: "UZ", 
    iso3: "UZB", 
    dial_code: "+998", 
    capital_cn: "塔什干", 
    capital_en: "Tashkent", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".uz", 
    timezone: "Asia/Tashkent", 
    currency_code: "UZS", 
    currency_name_cn: "乌兹别克斯坦索姆",
    currency_symbol: "so'm",
    language_cn: ["乌兹别克语"],
    language_en: ["Uzbek"],
    religion: ["伊斯兰教"],
    area_km2: 447400,
    population: 34000000,
    major_ports: [],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "尊重长者",
      "款待重要",
      "避免左手",
      "建立信任关键"
    ],
    major_holidays: ["新年(1月1日)", "纳吾肉孜节(3月21日)", "独立日(9月1日)", "宪法日(12月8日)"],
    trade_notes: [
      "棉花出口大国",
      "俄语仍通用",
      "官僚主义存在",
      "现金交易多"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "吉尔吉斯斯坦", 
    name_en: "Kyrgyzstan", 
    iso2: "KG", 
    iso3: "KGZ", 
    dial_code: "+996", 
    capital_cn: "比什凯克", 
    capital_en: "Bishkek", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".kg", 
    timezone: "Asia/Bishkek", 
    currency_code: "KGS", 
    currency_name_cn: "吉尔吉斯斯坦索姆",
    currency_symbol: "с",
    language_cn: ["吉尔吉斯语", "俄语"],
    language_en: ["Kyrgyz", "Russian"],
    religion: ["伊斯兰教", "基督教"],
    area_km2: 199951,
    population: 6600000,
    major_ports: [],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "热情好客",
      "尊重传统",
      "茶文化重要",
      "关系导向"
    ],
    major_holidays: ["新年(1月1日)", "国际妇女节(3月8日)", "纳吾肉孜节(3月21日)", "独立日(8月31日)"],
    trade_notes: [
      "黄金出口重要",
      "中国贸易增长",
      "基础设施发展中",
      "山地物流挑战"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "塔吉克斯坦", 
    name_en: "Tajikistan", 
    iso2: "TJ", 
    iso3: "TJK", 
    dial_code: "+992", 
    capital_cn: "杜尚别", 
    capital_en: "Dushanbe", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".tj", 
    timezone: "Asia/Dushanbe", 
    currency_code: "TJS", 
    currency_name_cn: "塔吉克斯坦索莫尼",
    currency_symbol: "ЅМ",
    language_cn: ["塔吉克语"],
    language_en: ["Tajik"],
    religion: ["伊斯兰教"],
    area_km2: 143100,
    population: 9500000,
    major_ports: [],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "尊重伊斯兰传统",
      "热情款待",
      "等级观念",
      "耐心重要"
    ],
    major_holidays: ["新年(1月1日)", "纳吾肉孜节(3月21日)", "独立日(9月9日)"],
    trade_notes: [
      "铝和棉花出口",
      "水电资源丰富",
      "基础设施薄弱",
      "依赖侨汇"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "土库曼斯坦", 
    name_en: "Turkmenistan", 
    iso2: "TM", 
    iso3: "TKM", 
    dial_code: "+993", 
    capital_cn: "阿什哈巴德", 
    capital_en: "Ashgabat", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".tm", 
    timezone: "Asia/Ashgabat", 
    currency_code: "TMT", 
    currency_name_cn: "土库曼斯坦马纳特",
    currency_symbol: "m",
    language_cn: ["土库曼语"],
    language_en: ["Turkmen"],
    religion: ["伊斯兰教"],
    area_km2: 488100,
    population: 6000000,
    major_ports: ["土库曼巴希港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "正式保守",
      "尊重传统",
      "避免政治话题",
      "礼物交换"
    ],
    major_holidays: ["新年(1月1日)", "独立日(10月27日)", "中立日(12月12日)"],
    trade_notes: [
      "天然气资源丰富",
      "国家控制经济",
      "签证困难",
      "现金经济"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "阿富汗", 
    name_en: "Afghanistan", 
    iso2: "AF", 
    iso3: "AFG", 
    dial_code: "+93", 
    capital_cn: "喀布尔", 
    capital_en: "Kabul", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".af", 
    timezone: "Asia/Kabul", 
    currency_code: "AFN", 
    currency_name_cn: "阿富汗尼",
    currency_symbol: "؋",
    language_cn: ["达里语", "普什图语"],
    language_en: ["Dari", "Pashto"],
    religion: ["伊斯兰教"],
    area_km2: 652230,
    population: 38900000,
    major_ports: [],
    business_hours: "周六至周三 8:00-16:00",
    business_etiquette: [
      "尊重伊斯兰传统",
      "男女分开",
      "建立信任缓慢",
      "避免左手"
    ],
    major_holidays: ["新年(3月21日)", "独立日(8月19日)", "开斋节", "宰牲节"],
    trade_notes: [
      "安全形势复杂",
      "现金经济",
      "基础设施薄弱",
      "部落影响大"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "伊朗", 
    name_en: "Iran", 
    iso2: "IR", 
    iso3: "IRN", 
    dial_code: "+98", 
    capital_cn: "德黑兰", 
    capital_en: "Tehran", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".ir", 
    timezone: "Asia/Tehran", 
    currency_code: "IRR", 
    currency_name_cn: "伊朗里亚尔",
    currency_symbol: "﷼",
    language_cn: ["波斯语"],
    language_en: ["Persian"],
    religion: ["伊斯兰教(什叶派)"],
    area_km2: 1648195,
    population: 83900000,
    major_ports: ["阿巴斯港", "伊玛目霍梅尼港"],
    business_hours: "周六至周三 8:00-16:00",
    business_etiquette: [
      "建立个人关系",
      "耐心谈判",
      "避免左手",
      "尊重伊斯兰习俗"
    ],
    major_holidays: ["诺鲁孜节(3月21日)", "伊斯兰革命日(2月11日)", "开斋节"],
    trade_notes: [
      "制裁影响贸易",
      "石油经济",
      "波斯语重要",
      "关系网络关键"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "230V"
  },
  { 
    name_cn: "伊拉克", 
    name_en: "Iraq", 
    iso2: "IQ", 
    iso3: "IRQ", 
    dial_code: "+964", 
    capital_cn: "巴格达", 
    capital_en: "Baghdad", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".iq", 
    timezone: "Asia/Baghdad", 
    currency_code: "IQD", 
    currency_name_cn: "伊拉克第纳尔",
    currency_symbol: "ع.د",
    language_cn: ["阿拉伯语", "库尔德语"],
    language_en: ["Arabic", "Kurdish"],
    religion: ["伊斯兰教"],
    area_km2: 438317,
    population: 40200000,
    major_ports: ["乌姆盖萨尔港", "巴士拉港"],
    business_hours: "周日至周四 8:00-15:00",
    business_etiquette: [
      "建立信任重要",
      "尊重部落传统",
      "避免左手",
      "耐心必要"
    ],
    major_holidays: ["新年(1月1日)", "军队日(1月6日)", "国庆日(10月3日)", "开斋节"],
    trade_notes: [
      "石油主导经济",
      "安全考虑重要",
      "现金交易普遍",
      "基础设施重建中"
    ],
    driving_side: "right",
    power_plug: "C/D/G",
    voltage: "230V"
  },
  { 
    name_cn: "叙利亚", 
    name_en: "Syria", 
    iso2: "SY", 
    iso3: "SYR", 
    dial_code: "+963", 
    capital_cn: "大马士革", 
    capital_en: "Damascus", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".sy", 
    timezone: "Asia/Damascus", 
    currency_code: "SYP", 
    currency_name_cn: "叙利亚镑",
    currency_symbol: "£",
    language_cn: ["阿拉伯语"],
    language_en: ["Arabic"],
    religion: ["伊斯兰教", "基督教"],
    area_km2: 185180,
    population: 17500000,
    major_ports: ["拉塔基亚港", "塔尔图斯港"],
    business_hours: "周日至周四 8:00-15:00",
    business_etiquette: [
      "关系优先",
      "款待文化",
      "避免政治话题",
      "耐心谈判"
    ],
    major_holidays: ["新年(1月1日)", "独立日(4月17日)", "烈士节(5月6日)", "开斋节"],
    trade_notes: [
      "战争影响严重",
      "制裁限制",
      "基础设施受损",
      "贸易风险高"
    ],
    driving_side: "right",
    power_plug: "C/E/L",
    voltage: "220V"
  },
  { 
    name_cn: "黎巴嫩", 
    name_en: "Lebanon", 
    iso2: "LB", 
    iso3: "LBN", 
    dial_code: "+961", 
    capital_cn: "贝鲁特", 
    capital_en: "Beirut", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".lb", 
    timezone: "Asia/Beirut", 
    currency_code: "LBP", 
    currency_name_cn: "黎巴嫩镑",
    currency_symbol: "ل.ل",
    language_cn: ["阿拉伯语", "法语"],
    language_en: ["Arabic", "French"],
    religion: ["伊斯兰教", "基督教"],
    area_km2: 10452,
    population: 6800000,
    major_ports: ["贝鲁特港", "的黎波里港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "多语言能力",
      "社交重要",
      "着装时尚",
      "灵活变通"
    ],
    major_holidays: ["新年(1月1日)", "劳动节(5月1日)", "独立日(11月22日)"],
    trade_notes: [
      "银行业发达",
      "法语英语通用",
      "关系导向强",
      "经济挑战多"
    ],
    driving_side: "right",
    power_plug: "C/D/G",
    voltage: "230V"
  },
  { 
    name_cn: "约旦", 
    name_en: "Jordan", 
    iso2: "JO", 
    iso3: "JOR", 
    dial_code: "+962", 
    capital_cn: "安曼", 
    capital_en: "Amman", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".jo", 
    timezone: "Asia/Amman", 
    currency_code: "JOD", 
    currency_name_cn: "约旦第纳尔",
    currency_symbol: "د.ا",
    language_cn: ["阿拉伯语"],
    language_en: ["Arabic"],
    religion: ["伊斯兰教", "基督教"],
    area_km2: 89342,
    population: 10200000,
    major_ports: ["亚喀巴港"],
    business_hours: "周日至周四 8:30-15:30",
    business_etiquette: [
      "握手问候",
      "尊重王室",
      "建立关系重要",
      "保守着装"
    ],
    major_holidays: ["新年(1月1日)", "劳动节(5月1日)", "独立日(5月25日)", "开斋节"],
    trade_notes: [
      "英语广泛使用",
      "稳定的商业环境",
      "服务业发达",
      "地区贸易枢纽"
    ],
    driving_side: "right",
    power_plug: "C/D/F/G/J",
    voltage: "230V"
  },
  { 
    name_cn: "科威特", 
    name_en: "Kuwait", 
    iso2: "KW", 
    iso3: "KWT", 
    dial_code: "+965", 
    capital_cn: "科威特城", 
    capital_en: "Kuwait City", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".kw", 
    timezone: "Asia/Kuwait", 
    currency_code: "KWD", 
    currency_name_cn: "科威特第纳尔",
    currency_symbol: "د.ك",
    language_cn: ["阿拉伯语"],
    language_en: ["Arabic"],
    religion: ["伊斯兰教"],
    area_km2: 17818,
    population: 4300000,
    major_ports: ["舒韦赫港", "舒艾巴港"],
    business_hours: "周日至周四 8:00-15:00",
    business_etiquette: [
      "尊重伊斯兰传统",
      "建立个人关系",
      "避免左手",
      "款待重要"
    ],
    major_holidays: ["新年(1月1日)", "国庆日(2月25日)", "解放日(2月26日)", "开斋节"],
    trade_notes: [
      "石油经济主导",
      "免税购物天堂",
      "决策层级化",
      "外籍劳工多"
    ],
    driving_side: "right",
    power_plug: "G",
    voltage: "240V"
  },
  { 
    name_cn: "巴林", 
    name_en: "Bahrain", 
    iso2: "BH", 
    iso3: "BHR", 
    dial_code: "+973", 
    capital_cn: "麦纳麦", 
    capital_en: "Manama", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".bh", 
    timezone: "Asia/Bahrain", 
    currency_code: "BHD", 
    currency_name_cn: "巴林第纳尔",
    currency_symbol: ".د.ب",
    language_cn: ["阿拉伯语"],
    language_en: ["Arabic"],
    religion: ["伊斯兰教"],
    area_km2: 765,
    population: 1700000,
    major_ports: ["米纳萨勒曼港"],
    business_hours: "周日至周四 8:00-15:00",
    business_etiquette: [
      "重视个人关系",
      "尊重伊斯兰习俗",
      "英语通用",
      "商务相对开放"
    ],
    major_holidays: ["新年(1月1日)", "国庆日(12月16日)", "开斋节", "宰牲节"],
    trade_notes: [
      "金融中心",
      "相对自由开放",
      "外籍人口多",
      "周末是周五周六"
    ],
    driving_side: "right",
    power_plug: "G",
    voltage: "230V"
  },
  { 
    name_cn: "卡塔尔", 
    name_en: "Qatar", 
    iso2: "QA", 
    iso3: "QAT", 
    dial_code: "+974", 
    capital_cn: "多哈", 
    capital_en: "Doha", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".qa", 
    timezone: "Asia/Qatar", 
    currency_code: "QAR", 
    currency_name_cn: "卡塔尔里亚尔",
    currency_symbol: "﷼",
    language_cn: ["阿拉伯语"],
    language_en: ["Arabic"],
    religion: ["伊斯兰教"],
    area_km2: 11586,
    population: 2900000,
    major_ports: ["哈马德港"],
    business_hours: "周日至周四 7:30-14:30",
    business_etiquette: [
      "建立信任关键",
      "尊重当地习俗",
      "耐心谈判",
      "重视款待"
    ],
    major_holidays: ["新年(1月1日)", "体育日(2月第二个周二)", "国庆日(12月18日)", "开斋节"],
    trade_notes: [
      "天然气出口大国",
      "基础设施先进",
      "2022世界杯主办国",
      "航空枢纽"
    ],
    driving_side: "right",
    power_plug: "G",
    voltage: "240V"
  },
  { 
    name_cn: "阿曼", 
    name_en: "Oman", 
    iso2: "OM", 
    iso3: "OMN", 
    dial_code: "+968", 
    capital_cn: "马斯喀特", 
    capital_en: "Muscat", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".om", 
    timezone: "Asia/Muscat", 
    currency_code: "OMR", 
    currency_name_cn: "阿曼里亚尔",
    currency_symbol: "﷼",
    language_cn: ["阿拉伯语"],
    language_en: ["Arabic"],
    religion: ["伊斯兰教"],
    area_km2: 309500,
    population: 5100000,
    major_ports: ["苏丹卡布斯港", "塞拉莱港"],
    business_hours: "周日至周四 8:00-15:00",
    business_etiquette: [
      "保守传统",
      "尊重苏丹",
      "耐心重要",
      "关系导向"
    ],
    major_holidays: ["新年(1月1日)", "国庆日(11月18日)", "苏丹生日(11月19日)", "开斋节"],
    trade_notes: [
      "石油天然气经济",
      "战略位置重要",
      "旅游业发展中",
      "传统与现代结合"
    ],
    driving_side: "right",
    power_plug: "G",
    voltage: "240V"
  },
  { 
    name_cn: "也门", 
    name_en: "Yemen", 
    iso2: "YE", 
    iso3: "YEM", 
    dial_code: "+967", 
    capital_cn: "萨那", 
    capital_en: "Sana'a", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".ye", 
    timezone: "Asia/Aden", 
    currency_code: "YER", 
    currency_name_cn: "也门里亚尔",
    currency_symbol: "﷼",
    language_cn: ["阿拉伯语"],
    language_en: ["Arabic"],
    religion: ["伊斯兰教"],
    area_km2: 527968,
    population: 29800000,
    major_ports: ["亚丁港", "荷台达港"],
    business_hours: "周六至周三 8:00-14:00",
    business_etiquette: [
      "部落传统重要",
      "建立信任缓慢",
      "款待文化",
      "保守社会"
    ],
    major_holidays: ["新年(1月1日)", "劳动节(5月1日)", "统一日(5月22日)", "革命日(9月26日)"],
    trade_notes: [
      "安全形势严峻",
      "经济困难",
      "咖啡出口传统",
      "基础设施薄弱"
    ],
    driving_side: "right",
    power_plug: "A/D/G",
    voltage: "230V"
  },
  { 
    name_cn: "塞浦路斯", 
    name_en: "Cyprus", 
    iso2: "CY", 
    iso3: "CYP", 
    dial_code: "+357", 
    capital_cn: "尼科西亚", 
    capital_en: "Nicosia", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".cy", 
    timezone: "Asia/Nicosia", 
    currency_code: "EUR", 
    currency_name_cn: "欧元",
    currency_symbol: "€",
    language_cn: ["希腊语", "土耳其语"],
    language_en: ["Greek", "Turkish"],
    religion: ["东正教", "伊斯兰教"],
    area_km2: 9251,
    population: 1200000,
    major_ports: ["利马索尔港", "拉纳卡港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "握手问候",
      "重视个人关系",
      "时间观念灵活",
      "英语广泛使用"
    ],
    major_holidays: ["新年(1月1日)", "独立日(10月1日)", "希腊国庆日(3月25日)", "复活节"],
    trade_notes: [
      "欧盟成员国",
      "服务业发达",
      "离岸金融中心",
      "旅游业重要"
    ],
    driving_side: "left",
    power_plug: "G",
    voltage: "240V"
  },
  { 
    name_cn: "格鲁吉亚", 
    name_en: "Georgia", 
    iso2: "GE", 
    iso3: "GEO", 
    dial_code: "+995", 
    capital_cn: "第比利斯", 
    capital_en: "Tbilisi", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".ge", 
    timezone: "Asia/Tbilisi", 
    currency_code: "GEL", 
    currency_name_cn: "格鲁吉亚拉里",
    currency_symbol: "₾",
    language_cn: ["格鲁吉亚语"],
    language_en: ["Georgian"],
    religion: ["东正教"],
    area_km2: 69700,
    population: 3700000,
    major_ports: ["巴统港", "波季港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "热情好客",
      "重视敬酒文化",
      "尊重长者",
      "关系导向"
    ],
    major_holidays: ["新年(1月1日)", "东正教圣诞节(1月7日)", "独立日(5月26日)", "圣乔治日(11月23日)"],
    trade_notes: [
      "葡萄酒出口国",
      "旅游业增长",
      "改革开放政策",
      "地理位置战略"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "亚美尼亚", 
    name_en: "Armenia", 
    iso2: "AM", 
    iso3: "ARM", 
    dial_code: "+374", 
    capital_cn: "埃里温", 
    capital_en: "Yerevan", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".am", 
    timezone: "Asia/Yerevan", 
    currency_code: "AMD", 
    currency_name_cn: "亚美尼亚德拉姆",
    currency_symbol: "֏",
    language_cn: ["亚美尼亚语"],
    language_en: ["Armenian"],
    religion: ["亚美尼亚使徒教会"],
    area_km2: 29743,
    population: 3000000,
    major_ports: [],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "握手问候",
      "重视款待",
      "尊重传统",
      "家庭价值观强"
    ],
    major_holidays: ["新年(1月1日)", "亚美尼亚圣诞节(1月6日)", "独立日(9月21日)", "种族灭绝纪念日(4月24日)"],
    trade_notes: [
      "内陆国家",
      "IT产业发展",
      "钻石加工业",
      "侨民网络强大"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "230V"
  },
  { 
    name_cn: "阿塞拜疆", 
    name_en: "Azerbaijan", 
    iso2: "AZ", 
    iso3: "AZE", 
    dial_code: "+994", 
    capital_cn: "巴库", 
    capital_en: "Baku", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".az", 
    timezone: "Asia/Baku", 
    currency_code: "AZN", 
    currency_name_cn: "阿塞拜疆马纳特",
    currency_symbol: "₼",
    language_cn: ["阿塞拜疆语"],
    language_en: ["Azerbaijani"],
    religion: ["伊斯兰教"],
    area_km2: 86600,
    population: 10100000,
    major_ports: ["巴库港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "重视关系",
      "茶文化重要",
      "尊重长者",
      "避免敏感话题"
    ],
    major_holidays: ["新年(1月1日)", "国际妇女节(3月8日)", "诺鲁孜节(3月20-21日)", "独立日(10月18日)"],
    trade_notes: [
      "石油天然气丰富",
      "里海沿岸国家",
      "交通枢纽地位",
      "与土耳其关系密切"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "220V"
  },
  { 
    name_cn: "蒙古", 
    name_en: "Mongolia", 
    iso2: "MN", 
    iso3: "MNG", 
    dial_code: "+976", 
    capital_cn: "乌兰巴托", 
    capital_en: "Ulaanbaatar", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".mn", 
    timezone: "Asia/Ulaanbaatar", 
    currency_code: "MNT", 
    currency_name_cn: "蒙古图格里克",
    currency_symbol: "₮",
    language_cn: ["蒙古语"],
    language_en: ["Mongolian"],
    religion: ["佛教", "萨满教"],
    area_km2: 1564110,
    population: 3300000,
    major_ports: [],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "尊重传统文化",
      "避免拒绝款待",
      "礼物交换重要",
      "耐心和尊重"
    ],
    major_holidays: ["新年(1月1日)", "白月节(1-2月)", "那达慕(7月11-13日)", "独立日(12月29日)"],
    trade_notes: [
      "矿产资源丰富",
      "内陆国家物流挑战",
      "与中俄贸易密切",
      "畜牧业传统重要"
    ],
    driving_side: "right",
    power_plug: "C/E",
    voltage: "230V"
  },
  { 
    name_cn: "朝鲜", 
    name_en: "North Korea", 
    iso2: "KP", 
    iso3: "PRK", 
    dial_code: "+850", 
    capital_cn: "平壤", 
    capital_en: "Pyongyang", 
    continent_cn: "亚洲", 
    continent_en: "Asia", 
    tld: ".kp", 
    timezone: "Asia/Pyongyang", 
    currency_code: "KPW", 
    currency_name_cn: "朝鲜圆",
    currency_symbol: "₩",
    language_cn: ["朝鲜语"],
    language_en: ["Korean"],
    religion: ["无宗教", "天道教", "佛教"],
    area_km2: 120538,
    population: 25800000,
    major_ports: ["南浦港", "清津港", "元山港"],
    business_hours: "周一至周六 8:00-17:00",
    business_etiquette: [
      "严格遵守当地规定",
      "尊重领导人",
      "正式着装",
      "避免敏感话题"
    ],
    major_holidays: ["新年(1月1日)", "金正日诞辰(2月16日)", "金日成诞辰(4月15日)", "建国日(9月9日)"],
    trade_notes: [
      "贸易受制裁影响",
      "国家控制经济",
      "特殊审批程序",
      "现金交易为主"
    ],
    driving_side: "right",
    power_plug: "C",
    voltage: "220V"
  },
  // 北美洲国家数据
  { 
    name_cn: "美国", 
    name_en: "United States", 
    iso2: "US", 
    iso3: "USA", 
    dial_code: "+1", 
    capital_cn: "华盛顿", 
    capital_en: "Washington, D.C.", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".us", 
    timezone: "America/New_York", 
    currency_code: "USD", 
    currency_name_cn: "美元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教", "天主教", "犹太教", "无宗教"],
    area_km2: 9833517,
    population: 331900000,
    major_ports: ["洛杉矶港", "长滩港", "纽约新泽西港", "萨凡纳港", "休斯顿港", "西雅图港"],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "准时非常重要",
      "握手要有力",
      "直接坦率的沟通风格",
      "注重个人空间"
    ],
    major_holidays: ["新年(1月1日)", "独立日(7月4日)", "感恩节(11月第4个周四)", "圣诞节(12月25日)"],
    trade_notes: [
      "重视合同和法律条款",
      "决策速度较快",
      "注重效率和结果",
      "电子邮件是主要沟通方式"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "加拿大", 
    name_en: "Canada", 
    iso2: "CA", 
    iso3: "CAN", 
    dial_code: "+1", 
    capital_cn: "渥太华", 
    capital_en: "Ottawa", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".ca", 
    timezone: "America/Toronto", 
    currency_code: "CAD", 
    currency_name_cn: "加拿大元",
    currency_symbol: "$",
    language_cn: ["英语", "法语"],
    language_en: ["English", "French"],
    religion: ["基督教", "天主教", "无宗教"],
    area_km2: 9984670,
    population: 38000000,
    major_ports: ["温哥华港", "蒙特利尔港", "哈利法克斯港", "鲁珀特王子港"],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "准时但不过分正式",
      "尊重多元文化",
      "避免与美国比较",
      "重视环保理念"
    ],
    major_holidays: ["新年(1月1日)", "维多利亚日(5月倒数第二个周一)", "加拿大日(7月1日)", "感恩节(10月第2个周一)", "圣诞节(12月25日)"],
    trade_notes: [
      "USMCA成员国",
      "资源出口大国",
      "双语环境(魁北克省法语)",
      "重视可持续发展"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "墨西哥", 
    name_en: "Mexico", 
    iso2: "MX", 
    iso3: "MEX", 
    dial_code: "+52", 
    capital_cn: "墨西哥城", 
    capital_en: "Mexico City", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".mx", 
    timezone: "America/Mexico_City", 
    currency_code: "MXN", 
    currency_name_cn: "墨西哥比索",
    currency_symbol: "$",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "基督教"],
    area_km2: 1964375,
    population: 128900000,
    major_ports: ["曼萨尼约港", "拉萨罗卡德纳斯港", "韦拉克鲁斯港", "阿尔塔米拉港"],
    business_hours: "周一至周五 9:00-18:00",
    business_etiquette: [
      "重视个人关系",
      "时间观念较灵活",
      "午餐是重要社交时间",
      "避免过于直接"
    ],
    major_holidays: ["新年(1月1日)", "宪法日(2月第1个周一)", "独立日(9月16日)", "亡灵节(11月1-2日)", "圣诞节(12月25日)"],
    trade_notes: [
      "USMCA成员国",
      "制造业发达",
      "家族企业文化",
      "重视面对面交流"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "127V"
  },
  { 
    name_cn: "危地马拉", 
    name_en: "Guatemala", 
    iso2: "GT", 
    iso3: "GTM", 
    dial_code: "+502", 
    capital_cn: "危地马拉城", 
    capital_en: "Guatemala City", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".gt", 
    timezone: "America/Guatemala", 
    currency_code: "GTQ", 
    currency_name_cn: "危地马拉格查尔",
    currency_symbol: "Q",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "基督教", "玛雅宗教"],
    area_km2: 108889,
    population: 17900000,
    major_ports: ["圣何塞港", "巴里奥斯港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "正式称呼重要",
      "建立信任需时间",
      "尊重等级制度",
      "避免敏感政治话题"
    ],
    major_holidays: ["新年(1月1日)", "圣周(3-4月)", "劳动节(5月1日)", "独立日(9月15日)", "圣诞节(12月25日)"],
    trade_notes: [
      "咖啡主要出口国",
      "纺织业重要",
      "美国是最大贸易伙伴",
      "基础设施发展中"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "伯利兹", 
    name_en: "Belize", 
    iso2: "BZ", 
    iso3: "BLZ", 
    dial_code: "+501", 
    capital_cn: "贝尔莫潘", 
    capital_en: "Belmopan", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".bz", 
    timezone: "America/Belize", 
    currency_code: "BZD", 
    currency_name_cn: "伯利兹元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["天主教", "基督教"],
    area_km2: 22966,
    population: 419000,
    major_ports: ["伯利兹港", "大溪港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "轻松友好氛围",
      "时间观念灵活",
      "英语为官方语言",
      "避免过于正式"
    ],
    major_holidays: ["新年(1月1日)", "英联邦日(5月24日)", "独立日(9月21日)", "圣诞节(12月25日)"],
    trade_notes: [
      "旅游业重要",
      "农产品出口",
      "离岸金融服务",
      "加勒比共同体成员"
    ],
    driving_side: "right",
    power_plug: "A/B/G",
    voltage: "110V/220V"
  },
  { 
    name_cn: "萨尔瓦多", 
    name_en: "El Salvador", 
    iso2: "SV", 
    iso3: "SLV", 
    dial_code: "+503", 
    capital_cn: "圣萨尔瓦多", 
    capital_en: "San Salvador", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".sv", 
    timezone: "America/El_Salvador", 
    currency_code: "USD", 
    currency_name_cn: "美元",
    currency_symbol: "$",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "基督教"],
    area_km2: 21041,
    population: 6500000,
    major_ports: ["阿卡胡特拉港", "拉乌尼翁港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "握手问候",
      "正式但友好",
      "家族企业多",
      "重视个人关系"
    ],
    major_holidays: ["新年(1月1日)", "圣周(3-4月)", "劳动节(5月1日)", "独立日(9月15日)", "圣诞节(12月25日)"],
    trade_notes: [
      "使用美元",
      "咖啡出口国",
      "纺织业发达",
      "侨汇经济重要"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "115V"
  },
  { 
    name_cn: "洪都拉斯", 
    name_en: "Honduras", 
    iso2: "HN", 
    iso3: "HND", 
    dial_code: "+504", 
    capital_cn: "特古西加尔巴", 
    capital_en: "Tegucigalpa", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".hn", 
    timezone: "America/Tegucigalpa", 
    currency_code: "HNL", 
    currency_name_cn: "洪都拉斯伦皮拉",
    currency_symbol: "L",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "基督教"],
    area_km2: 112492,
    population: 9900000,
    major_ports: ["科尔特斯港", "卡斯蒂利亚港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "尊重等级",
      "建立信任重要",
      "时间观念灵活",
      "正式着装"
    ],
    major_holidays: ["新年(1月1日)", "美洲日(4月14日)", "劳动节(5月1日)", "独立日(9月15日)", "圣诞节(12月25日)"],
    trade_notes: [
      "香蕉主要出口国",
      "咖啡产业重要",
      "纺织加工业",
      "基础设施薄弱"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "110V"
  },
  { 
    name_cn: "尼加拉瓜", 
    name_en: "Nicaragua", 
    iso2: "NI", 
    iso3: "NIC", 
    dial_code: "+505", 
    capital_cn: "马那瓜", 
    capital_en: "Managua", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".ni", 
    timezone: "America/Managua", 
    currency_code: "NIO", 
    currency_name_cn: "尼加拉瓜科多巴",
    currency_symbol: "C$",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "基督教"],
    area_km2: 130373,
    population: 6600000,
    major_ports: ["科林托港", "布拉夫港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "保守传统",
      "重视礼貌",
      "等级观念存在",
      "避免政治话题"
    ],
    major_holidays: ["新年(1月1日)", "圣周(3-4月)", "劳动节(5月1日)", "独立日(9月15日)", "圣诞节(12月25日)"],
    trade_notes: [
      "农产品出口为主",
      "咖啡重要出口品",
      "自由贸易区",
      "政治影响经济"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "哥斯达黎加", 
    name_en: "Costa Rica", 
    iso2: "CR", 
    iso3: "CRI", 
    dial_code: "+506", 
    capital_cn: "圣何塞", 
    capital_en: "San José", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".cr", 
    timezone: "America/Costa_Rica", 
    currency_code: "CRC", 
    currency_name_cn: "哥斯达黎加科朗",
    currency_symbol: "₡",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "基督教"],
    area_km2: 51100,
    population: 5100000,
    major_ports: ["利蒙港", "卡尔德拉港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "友好有礼",
      "环保意识强",
      "教育水平高",
      "避免冲突"
    ],
    major_holidays: ["新年(1月1日)", "圣周(3-4月)", "劳动节(5月1日)", "独立日(9月15日)", "圣诞节(12月25日)"],
    trade_notes: [
      "生态旅游发达",
      "高科技产业增长",
      "政治稳定",
      "无军队国家"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "巴拿马", 
    name_en: "Panama", 
    iso2: "PA", 
    iso3: "PAN", 
    dial_code: "+507", 
    capital_cn: "巴拿马城", 
    capital_en: "Panama City", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".pa", 
    timezone: "America/Panama", 
    currency_code: "PAB", 
    currency_name_cn: "巴拿马巴波亚",
    currency_symbol: "B/.",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "基督教"],
    area_km2: 75417,
    population: 4300000,
    major_ports: ["巴尔博亚港", "克里斯托瓦尔港", "曼萨尼约国际码头"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "正式但友好",
      "时间观念重要",
      "国际化程度高",
      "英语使用广泛"
    ],
    major_holidays: ["新年(1月1日)", "烈士节(1月9日)", "独立日(11月3日)", "母亲节(12月8日)", "圣诞节(12月25日)"],
    trade_notes: [
      "运河经济核心",
      "国际金融中心",
      "自由贸易区发达",
      "美元为法定货币"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "110V"
  },
  { 
    name_cn: "古巴", 
    name_en: "Cuba", 
    iso2: "CU", 
    iso3: "CUB", 
    dial_code: "+53", 
    capital_cn: "哈瓦那", 
    capital_en: "Havana", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".cu", 
    timezone: "America/Havana", 
    currency_code: "CUP", 
    currency_name_cn: "古巴比索",
    currency_symbol: "$",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "萨泰里阿教"],
    area_km2: 109884,
    population: 11300000,
    major_ports: ["哈瓦那港", "马里埃尔港", "圣地亚哥港"],
    business_hours: "周一至周五 8:30-17:30",
    business_etiquette: [
      "关系网络重要",
      "耐心必要",
      "避免政治话题",
      "礼物交换常见"
    ],
    major_holidays: ["解放日(1月1日)", "劳动节(5月1日)", "国家起义日(7月26日)", "独立日(10月10日)"],
    trade_notes: [
      "贸易受限制",
      "旅游业重要",
      "双货币体系",
      "国营企业主导"
    ],
    driving_side: "right",
    power_plug: "A/B/C/L",
    voltage: "110V/220V"
  },
  { 
    name_cn: "牙买加", 
    name_en: "Jamaica", 
    iso2: "JM", 
    iso3: "JAM", 
    dial_code: "+1-876", 
    capital_cn: "金斯敦", 
    capital_en: "Kingston", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".jm", 
    timezone: "America/Jamaica", 
    currency_code: "JMD", 
    currency_name_cn: "牙买加元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教", "拉斯塔法里教"],
    area_km2: 10991,
    population: 2700000,
    major_ports: ["金斯敦港", "蒙特哥贝港"],
    business_hours: "周一至周五 8:30-16:30",
    business_etiquette: [
      "轻松友好",
      "时间观念灵活",
      "尊重个人空间",
      "避免过于正式"
    ],
    major_holidays: ["新年(1月1日)", "解放日(8月1日)", "独立日(8月6日)", "国家英雄日(10月第3个周一)", "圣诞节(12月25日)"],
    trade_notes: [
      "旅游业支柱",
      "铝土矿出口",
      "音乐文化出口",
      "侨汇重要"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "110V"
  },
  { 
    name_cn: "海地", 
    name_en: "Haiti", 
    iso2: "HT", 
    iso3: "HTI", 
    dial_code: "+509", 
    capital_cn: "太子港", 
    capital_en: "Port-au-Prince", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".ht", 
    timezone: "America/Port-au-Prince", 
    currency_code: "HTG", 
    currency_name_cn: "海地古德",
    currency_symbol: "G",
    language_cn: ["法语", "海地克里奥尔语"],
    language_en: ["French", "Haitian Creole"],
    religion: ["天主教", "基督教", "伏都教"],
    area_km2: 27750,
    population: 11400000,
    major_ports: ["太子港"],
    business_hours: "周一至周五 8:00-16:00",
    business_etiquette: [
      "法语为官方语言",
      "正式礼貌",
      "耐心重要",
      "建立信任缓慢"
    ],
    major_holidays: ["独立日(1月1日)", "嘉年华(2月)", "劳动节(5月1日)", "海地国旗日(5月18日)"],
    trade_notes: [
      "最不发达国家之一",
      "纺织品出口",
      "基础设施薄弱",
      "援助依赖大"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "110V"
  },
  { 
    name_cn: "多米尼加", 
    name_en: "Dominican Republic", 
    iso2: "DO", 
    iso3: "DOM", 
    dial_code: "+1-809", 
    capital_cn: "圣多明各", 
    capital_en: "Santo Domingo", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".do", 
    timezone: "America/Santo_Domingo", 
    currency_code: "DOP", 
    currency_name_cn: "多米尼加比索",
    currency_symbol: "$",
    language_cn: ["西班牙语"],
    language_en: ["Spanish"],
    religion: ["天主教", "基督教"],
    area_km2: 48671,
    population: 10800000,
    major_ports: ["考塞多港", "海纳港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "热情友好",
      "重视个人关系",
      "时间观念灵活",
      "家族企业多"
    ],
    major_holidays: ["新年(1月1日)", "独立日(2月27日)", "圣周(3-4月)", "恢复日(8月16日)", "圣诞节(12月25日)"],
    trade_notes: [
      "旅游业发达",
      "自由贸易区",
      "雪茄出口",
      "美国重要贸易伙伴"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "110V"
  },
  { 
    name_cn: "巴哈马", 
    name_en: "Bahamas", 
    iso2: "BS", 
    iso3: "BHS", 
    dial_code: "+1-242", 
    capital_cn: "拿骚", 
    capital_en: "Nassau", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".bs", 
    timezone: "America/Nassau", 
    currency_code: "BSD", 
    currency_name_cn: "巴哈马元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教", "天主教"],
    area_km2: 13943,
    population: 393000,
    major_ports: ["拿骚港", "自由港"],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "英式礼仪影响",
      "商务休闲风格",
      "准时重要",
      "友好专业"
    ],
    major_holidays: ["新年(1月1日)", "独立日(7月10日)", "解放日(8月第1个周一)", "圣诞节(12月25日)"],
    trade_notes: [
      "旅游业为主",
      "离岸金融中心",
      "与美元挂钩",
      "免税购物"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "巴巴多斯", 
    name_en: "Barbados", 
    iso2: "BB", 
    iso3: "BRB", 
    dial_code: "+1-246", 
    capital_cn: "布里奇敦", 
    capital_en: "Bridgetown", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".bb", 
    timezone: "America/Barbados", 
    currency_code: "BBD", 
    currency_name_cn: "巴巴多斯元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教", "天主教"],
    area_km2: 430,
    population: 287000,
    major_ports: ["布里奇敦港"],
    business_hours: "周一至周五 8:00-16:30",
    business_etiquette: [
      "英式传统",
      "正式礼貌",
      "准时重要",
      "保守着装"
    ],
    major_holidays: ["新年(1月1日)", "英雄日(4月28日)", "独立日(11月30日)", "圣诞节(12月25日)"],
    trade_notes: [
      "旅游业发达",
      "朗姆酒出口",
      "教育水平高",
      "服务业为主"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "115V"
  },
  { 
    name_cn: "安提瓜和巴布达", 
    name_en: "Antigua and Barbuda", 
    iso2: "AG", 
    iso3: "ATG", 
    dial_code: "+1-268", 
    capital_cn: "圣约翰", 
    capital_en: "St. John's", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".ag", 
    timezone: "America/Antigua", 
    currency_code: "XCD", 
    currency_name_cn: "东加勒比元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教"],
    area_km2: 442,
    population: 98000,
    major_ports: ["圣约翰港"],
    business_hours: "周一至周五 8:00-16:00",
    business_etiquette: [
      "英式礼仪",
      "休闲氛围",
      "友好热情",
      "旅游服务意识"
    ],
    major_holidays: ["新年(1月1日)", "复活节(3-4月)", "独立日(11月1日)", "圣诞节(12月25日)"],
    trade_notes: [
      "旅游业主导",
      "投资入籍项目",
      "离岸金融",
      "游艇注册"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "230V"
  },
  { 
    name_cn: "圣基茨和尼维斯", 
    name_en: "Saint Kitts and Nevis", 
    iso2: "KN", 
    iso3: "KNA", 
    dial_code: "+1-869", 
    capital_cn: "巴斯特尔", 
    capital_en: "Basseterre", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".kn", 
    timezone: "America/St_Kitts", 
    currency_code: "XCD", 
    currency_name_cn: "东加勒比元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教"],
    area_km2: 261,
    population: 53000,
    major_ports: ["巴斯特尔港"],
    business_hours: "周一至周五 8:00-16:00",
    business_etiquette: [
      "正式有礼",
      "英国传统",
      "小型社区氛围",
      "重视教育"
    ],
    major_holidays: ["新年(1月1日)", "独立日(9月19日)", "圣诞节(12月25日)"],
    trade_notes: [
      "投资入籍先驱",
      "旅游业重要",
      "糖业历史",
      "金融服务"
    ],
    driving_side: "left",
    power_plug: "D/G",
    voltage: "230V"
  },
  { 
    name_cn: "多米尼克", 
    name_en: "Dominica", 
    iso2: "DM", 
    iso3: "DMA", 
    dial_code: "+1-767", 
    capital_cn: "罗索", 
    capital_en: "Roseau", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".dm", 
    timezone: "America/Dominica", 
    currency_code: "XCD", 
    currency_name_cn: "东加勒比元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["天主教", "基督教"],
    area_km2: 751,
    population: 72000,
    major_ports: ["罗索港"],
    business_hours: "周一至周五 8:00-16:00",
    business_etiquette: [
      "友好随和",
      "自然环保意识",
      "社区联系紧密",
      "传统价值观"
    ],
    major_holidays: ["新年(1月1日)", "独立日(11月3日)", "圣诞节(12月25日)"],
    trade_notes: [
      "生态旅游",
      "农产品出口",
      "投资入籍",
      "可再生能源"
    ],
    driving_side: "left",
    power_plug: "D/G",
    voltage: "230V"
  },
  { 
    name_cn: "圣卢西亚", 
    name_en: "Saint Lucia", 
    iso2: "LC", 
    iso3: "LCA", 
    dial_code: "+1-758", 
    capital_cn: "卡斯特里", 
    capital_en: "Castries", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".lc", 
    timezone: "America/St_Lucia", 
    currency_code: "XCD", 
    currency_name_cn: "东加勒比元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["天主教", "基督教"],
    area_km2: 617,
    population: 184000,
    major_ports: ["卡斯特里港", "维约堡港"],
    business_hours: "周一至周五 8:00-16:30",
    business_etiquette: [
      "轻松专业",
      "法语影响",
      "旅游服务导向",
      "友好开放"
    ],
    major_holidays: ["新年(1月1日)", "独立日(2月22日)", "嘉年华(7月)", "圣诞节(12月25日)"],
    trade_notes: [
      "旅游业支柱",
      "香蕉出口",
      "离岸金融",
      "投资项目"
    ],
    driving_side: "left",
    power_plug: "G",
    voltage: "230V"
  },
  { 
    name_cn: "圣文森特和格林纳丁斯", 
    name_en: "Saint Vincent and the Grenadines", 
    iso2: "VC", 
    iso3: "VCT", 
    dial_code: "+1-784", 
    capital_cn: "金斯敦", 
    capital_en: "Kingstown", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".vc", 
    timezone: "America/St_Vincent", 
    currency_code: "XCD", 
    currency_name_cn: "东加勒比元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教"],
    area_km2: 389,
    population: 111000,
    major_ports: ["金斯敦港"],
    business_hours: "周一至周五 8:00-16:00",
    business_etiquette: [
      "传统保守",
      "友好礼貌",
      "社区导向",
      "英式影响"
    ],
    major_holidays: ["新年(1月1日)", "独立日(10月27日)", "圣诞节(12月25日)"],
    trade_notes: [
      "农业出口",
      "游艇旅游",
      "离岸服务",
      "小型经济体"
    ],
    driving_side: "left",
    power_plug: "A/C/E/G/I/K",
    voltage: "230V"
  },
  { 
    name_cn: "格林纳达", 
    name_en: "Grenada", 
    iso2: "GD", 
    iso3: "GRD", 
    dial_code: "+1-473", 
    capital_cn: "圣乔治", 
    capital_en: "St. George's", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".gd", 
    timezone: "America/Grenada", 
    currency_code: "XCD", 
    currency_name_cn: "东加勒比元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["天主教", "基督教"],
    area_km2: 344,
    population: 113000,
    major_ports: ["圣乔治港"],
    business_hours: "周一至周五 8:00-16:00",
    business_etiquette: [
      "热情友好",
      "香料岛文化",
      "英式传统",
      "社区紧密"
    ],
    major_holidays: ["新年(1月1日)", "独立日(2月7日)", "嘉年华(8月)", "圣诞节(12月25日)"],
    trade_notes: [
      "香料出口(肉豆蔻)",
      "旅游业重要",
      "投资入籍",
      "农业传统"
    ],
    driving_side: "left",
    power_plug: "G",
    voltage: "230V"
  },
  { 
    name_cn: "格陵兰", 
    name_en: "Greenland", 
    iso2: "GL", 
    iso3: "GRL", 
    dial_code: "+299", 
    capital_cn: "努克", 
    capital_en: "Nuuk", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".gl", 
    timezone: "America/Godthab", 
    currency_code: "DKK", 
    currency_name_cn: "丹麦克朗",
    currency_symbol: "kr",
    language_cn: ["格陵兰语", "丹麦语"],
    language_en: ["Greenlandic", "Danish"],
    religion: ["基督教"],
    area_km2: 2166086,
    population: 56000,
    major_ports: ["努克港", "西西缪特港"],
    business_hours: "周一至周五 8:00-16:00",
    business_etiquette: [
      "尊重因纽特文化",
      "环保意识强",
      "社区导向",
      "丹麦影响"
    ],
    major_holidays: ["新年(1月1日)", "国庆日(6月21日)", "圣诞节(12月25日)"],
    trade_notes: [
      "渔业为主",
      "矿产潜力",
      "旅游业增长",
      "丹麦自治领"
    ],
    driving_side: "right",
    power_plug: "C/E/F/K",
    voltage: "230V"
  },
  { 
    name_cn: "百慕大", 
    name_en: "Bermuda", 
    iso2: "BM", 
    iso3: "BMU", 
    dial_code: "+1-441", 
    capital_cn: "汉密尔顿", 
    capital_en: "Hamilton", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".bm", 
    timezone: "Atlantic/Bermuda", 
    currency_code: "BMD", 
    currency_name_cn: "百慕大元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教"],
    area_km2: 54,
    population: 64000,
    major_ports: ["汉密尔顿港", "圣乔治港"],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "英式正式",
      "保守着装",
      "准时重要",
      "国际化程度高"
    ],
    major_holidays: ["新年(1月1日)", "百慕大日(5月24日)", "英女王生日(6月)", "圣诞节(12月25日)"],
    trade_notes: [
      "再保险中心",
      "离岸金融",
      "旅游业发达",
      "英国海外领地"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "开曼群岛", 
    name_en: "Cayman Islands", 
    iso2: "KY", 
    iso3: "CYM", 
    dial_code: "+1-345", 
    capital_cn: "乔治敦", 
    capital_en: "George Town", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".ky", 
    timezone: "America/Cayman", 
    currency_code: "KYD", 
    currency_name_cn: "开曼群岛元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教"],
    area_km2: 264,
    population: 66000,
    major_ports: ["乔治敦港"],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "国际商务标准",
      "专业正式",
      "保密意识强",
      "效率导向"
    ],
    major_holidays: ["新年(1月1日)", "宪法日(7月第1个周一)", "圣诞节(12月25日)"],
    trade_notes: [
      "全球金融中心",
      "零税率",
      "对冲基金中心",
      "英国海外领地"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "英属维尔京群岛", 
    name_en: "British Virgin Islands", 
    iso2: "VG", 
    iso3: "VGB", 
    dial_code: "+1-284", 
    capital_cn: "罗德城", 
    capital_en: "Road Town", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".vg", 
    timezone: "America/Tortola", 
    currency_code: "USD", 
    currency_name_cn: "美元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教"],
    area_km2: 151,
    population: 30000,
    major_ports: ["罗德城港"],
    business_hours: "周一至周五 9:00-17:00",
    business_etiquette: [
      "离岸业务专业",
      "英式传统",
      "保密严格",
      "国际化"
    ],
    major_holidays: ["新年(1月1日)", "领土日(7月1日)", "圣诞节(12月25日)"],
    trade_notes: [
      "离岸公司注册",
      "金融服务",
      "游艇产业",
      "旅游业"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "110V"
  },
  { 
    name_cn: "美属维尔京群岛", 
    name_en: "U.S. Virgin Islands", 
    iso2: "VI", 
    iso3: "VIR", 
    dial_code: "+1-340", 
    capital_cn: "夏洛特阿马利亚", 
    capital_en: "Charlotte Amalie", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".vi", 
    timezone: "America/St_Thomas", 
    currency_code: "USD", 
    currency_name_cn: "美元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教"],
    area_km2: 346,
    population: 104000,
    major_ports: ["夏洛特阿马利亚港", "克里斯琴斯特德港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "美式风格",
      "休闲友好",
      "旅游服务导向",
      "多元文化"
    ],
    major_holidays: ["新年(1月1日)", "马丁路德金日(1月第3个周一)", "独立日(7月4日)", "圣诞节(12月25日)"],
    trade_notes: [
      "免税购物",
      "旅游业主导",
      "朗姆酒生产",
      "美国领地"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "110V"
  },
  { 
    name_cn: "波多黎各", 
    name_en: "Puerto Rico", 
    iso2: "PR", 
    iso3: "PRI", 
    dial_code: "+1-787", 
    capital_cn: "圣胡安", 
    capital_en: "San Juan", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".pr", 
    timezone: "America/Puerto_Rico", 
    currency_code: "USD", 
    currency_name_cn: "美元",
    currency_symbol: "$",
    language_cn: ["西班牙语", "英语"],
    language_en: ["Spanish", "English"],
    religion: ["天主教", "基督教"],
    area_km2: 9104,
    population: 3200000,
    major_ports: ["圣胡安港", "庞塞港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "双语环境",
      "拉丁文化",
      "美式影响",
      "关系导向"
    ],
    major_holidays: ["新年(1月1日)", "三王节(1月6日)", "独立日(7月4日)", "发现日(11月19日)", "圣诞节(12月25日)"],
    trade_notes: [
      "制药业发达",
      "美国自治领",
      "税收优惠",
      "服务业重要"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "圣皮埃尔和密克隆", 
    name_en: "Saint Pierre and Miquelon", 
    iso2: "PM", 
    iso3: "SPM", 
    dial_code: "+508", 
    capital_cn: "圣皮埃尔", 
    capital_en: "Saint-Pierre", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".pm", 
    timezone: "America/Miquelon", 
    currency_code: "EUR", 
    currency_name_cn: "欧元",
    currency_symbol: "€",
    language_cn: ["法语"],
    language_en: ["French"],
    religion: ["天主教"],
    area_km2: 242,
    population: 6000,
    major_ports: ["圣皮埃尔港"],
    business_hours: "周一至周五 8:30-17:30",
    business_etiquette: [
      "法式礼仪",
      "正式传统",
      "小社区氛围",
      "渔业文化"
    ],
    major_holidays: ["新年(1月1日)", "法国国庆日(7月14日)", "圣诞节(12月25日)"],
    trade_notes: [
      "渔业为主",
      "法国海外领地",
      "欧元区",
      "与加拿大贸易"
    ],
    driving_side: "right",
    power_plug: "E",
    voltage: "230V"
  },
  { 
    name_cn: "特克斯和凯科斯群岛", 
    name_en: "Turks and Caicos Islands", 
    iso2: "TC", 
    iso3: "TCA", 
    dial_code: "+1-649", 
    capital_cn: "科伯恩城", 
    capital_en: "Cockburn Town", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".tc", 
    timezone: "America/Grand_Turk", 
    currency_code: "USD", 
    currency_name_cn: "美元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教"],
    area_km2: 948,
    population: 39000,
    major_ports: ["大特克港", "普罗维登西亚莱斯港"],
    business_hours: "周一至周五 8:30-16:30",
    business_etiquette: [
      "英式传统",
      "旅游导向",
      "轻松专业",
      "国际化"
    ],
    major_holidays: ["新年(1月1日)", "英联邦日(3月第2个周一)", "英女王生日(6月)", "圣诞节(12月25日)"],
    trade_notes: [
      "高端旅游",
      "离岸金融",
      "房地产投资",
      "英国海外领地"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "120V"
  },
  { 
    name_cn: "马提尼克", 
    name_en: "Martinique", 
    iso2: "MQ", 
    iso3: "MTQ", 
    dial_code: "+596", 
    capital_cn: "法兰西堡", 
    capital_en: "Fort-de-France", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".mq", 
    timezone: "America/Martinique", 
    currency_code: "EUR", 
    currency_name_cn: "欧元",
    currency_symbol: "€",
    language_cn: ["法语"],
    language_en: ["French"],
    religion: ["天主教"],
    area_km2: 1128,
    population: 375000,
    major_ports: ["法兰西堡港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "法式文化",
      "正式礼貌",
      "时间观念灵活",
      "美食文化重要"
    ],
    major_holidays: ["新年(1月1日)", "狂欢节(2-3月)", "法国国庆日(7月14日)", "圣诞节(12月25日)"],
    trade_notes: [
      "朗姆酒出口",
      "法国海外省",
      "欧盟成员",
      "旅游业发达"
    ],
    driving_side: "right",
    power_plug: "C/D/E",
    voltage: "220V"
  },
  { 
    name_cn: "瓜德罗普", 
    name_en: "Guadeloupe", 
    iso2: "GP", 
    iso3: "GLP", 
    dial_code: "+590", 
    capital_cn: "巴斯特尔", 
    capital_en: "Basse-Terre", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".gp", 
    timezone: "America/Guadeloupe", 
    currency_code: "EUR", 
    currency_name_cn: "欧元",
    currency_symbol: "€",
    language_cn: ["法语"],
    language_en: ["French"],
    religion: ["天主教"],
    area_km2: 1705,
    population: 400000,
    major_ports: ["皮特尔角港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "法式传统",
      "克里奥尔文化",
      "休闲氛围",
      "家庭价值观"
    ],
    major_holidays: ["新年(1月1日)", "狂欢节(2-3月)", "废奴日(5月27日)", "法国国庆日(7月14日)", "圣诞节(12月25日)"],
    trade_notes: [
      "香蕉和糖出口",
      "法国海外省",
      "欧盟成员",
      "旅游业重要"
    ],
    driving_side: "right",
    power_plug: "C/D/E",
    voltage: "230V"
  },
  { 
    name_cn: "荷属圣马丁", 
    name_en: "Sint Maarten", 
    iso2: "SX", 
    iso3: "SXM", 
    dial_code: "+1-721", 
    capital_cn: "菲利普斯堡", 
    capital_en: "Philipsburg", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".sx", 
    timezone: "America/Lower_Princes", 
    currency_code: "ANG", 
    currency_name_cn: "荷属安的列斯盾",
    currency_symbol: "ƒ",
    language_cn: ["荷兰语", "英语"],
    language_en: ["Dutch", "English"],
    religion: ["基督教"],
    area_km2: 34,
    population: 42000,
    major_ports: ["菲利普斯堡港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "国际化氛围",
      "旅游服务导向",
      "多语言环境",
      "轻松专业"
    ],
    major_holidays: ["新年(1月1日)", "国王日(4月27日)", "圣马丁日(11月11日)", "圣诞节(12月25日)"],
    trade_notes: [
      "免税购物",
      "邮轮港口",
      "旅游业主导",
      "荷兰王国构成国"
    ],
    driving_side: "right",
    power_plug: "A/B",
    voltage: "110V"
  },
  { 
    name_cn: "阿鲁巴", 
    name_en: "Aruba", 
    iso2: "AW", 
    iso3: "ABW", 
    dial_code: "+297", 
    capital_cn: "奥拉涅斯塔德", 
    capital_en: "Oranjestad", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".aw", 
    timezone: "America/Aruba", 
    currency_code: "AWG", 
    currency_name_cn: "阿鲁巴弗罗林",
    currency_symbol: "ƒ",
    language_cn: ["荷兰语", "帕皮阿门托语"],
    language_en: ["Dutch", "Papiamento"],
    religion: ["天主教"],
    area_km2: 180,
    population: 107000,
    major_ports: ["奥拉涅斯塔德港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "多元文化",
      "友好开放",
      "时间观念灵活",
      "旅游服务意识"
    ],
    major_holidays: ["新年(1月1日)", "国旗日(3月18日)", "国王日(4月27日)", "圣诞节(12月25日)"],
    trade_notes: [
      "旅游业核心",
      "炼油业",
      "离岸金融",
      "荷兰王国构成国"
    ],
    driving_side: "right",
    power_plug: "A/B/F",
    voltage: "127V"
  },
  { 
    name_cn: "库拉索", 
    name_en: "Curaçao", 
    iso2: "CW", 
    iso3: "CUW", 
    dial_code: "+599", 
    capital_cn: "威廉斯塔德", 
    capital_en: "Willemstad", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".cw", 
  { 
    name_cn: "特立尼达和多巴哥", 
    name_en: "Trinidad and Tobago", 
    iso2: "TT", 
    iso3: "TTO", 
    dial_code: "+1-868", 
    capital_cn: "西班牙港", 
    capital_en: "Port of Spain", 
    continent_cn: "北美洲", 
    continent_en: "North America", 
    tld: ".tt", 
    timezone: "America/Port_of_Spain", 
    currency_code: "TTD", 
    currency_name_cn: "特立尼达和多巴哥元",
    currency_symbol: "$",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教", "印度教", "伊斯兰教"],
    area_km2: 5130,
    population: 1400000,
    major_ports: ["西班牙港", "利萨斯角港"],
    business_hours: "周一至周五 8:00-16:00",
    business_etiquette: [
      "多元文化融合",
      "轻松友好",
      "时间观念灵活",
      "嘉年华文化"
    ],
    major_holidays: ["新年(1月1日)", "嘉年华(2-3月)", "印度到达日(5月30日)", "独立日(8月31日)", "圣诞节(12月25日)"],
    trade_notes: [
      "石油天然气出口",
      "加勒比最工业化",
      "金融服务发达",
      "文化多样性"
    ],
    driving_side: "left",
    power_plug: "A/B",
    voltage: "115V"
  },
  { 
    name_cn: "德国", 
    name_en: "Germany", 
    iso2: "DE", 
    iso3: "DEU", 
    dial_code: "+49", 
    capital_cn: "柏林", 
    capital_en: "Berlin", 
    continent_cn: "欧洲", 
    continent_en: "Europe", 
    tld: ".de", 
    timezone: "Europe/Berlin", 
    currency_code: "EUR", 
    currency_name_cn: "欧元",
    currency_symbol: "€",
    language_cn: ["德语"],
    language_en: ["German"],
    religion: ["基督教", "天主教", "无宗教"],
    area_km2: 357022,
    population: 83200000,
    major_ports: ["汉堡港", "不来梅港", "威廉港"],
    business_hours: "周一至周五 8:00-17:00",
    business_etiquette: [
      "极其准时",
      "正式称呼(使用头衔)",
      "握手要坚定",
      "重视隐私"
    ],
    major_holidays: ["新年(1月1日)", "复活节(3-4月)", "劳动节(5月1日)", "圣诞节(12月25-26日)"],
    trade_notes: [
      "高度重视质量和标准",
      "喜欢详细的计划和文档",
      "决策基于数据和事实",
      "守时是商务基本要求"
    ],
    driving_side: "right",
    power_plug: "C/F",
    voltage: "230V"
  },
  { 
    name_cn: "英国", 
    name_en: "United Kingdom", 
    iso2: "GB", 
    iso3: "GBR", 
    dial_code: "+44", 
    capital_cn: "伦敦", 
    capital_en: "London", 
    continent_cn: "欧洲", 
    continent_en: "Europe", 
    tld: ".uk", 
    timezone: "Europe/London", 
    currency_code: "GBP", 
    currency_name_cn: "英镑",
    currency_symbol: "£",
    language_cn: ["英语"],
    language_en: ["English"],
    religion: ["基督教", "无宗教", "伊斯兰教"],
    area_km2: 242495,
    population: 67500000,
    major_ports: ["费利克斯托港", "南安普顿港", "伦敦港", "利物浦港"],
    business_hours: "周一至周五 9:00-17:30",
    business_etiquette: [
      "保持礼貌和含蓄",
      "避免过于直接",
      "重视幽默感",
      "着装相对正式"
    ],
    major_holidays: ["新年(1月1日)", "复活节(3-4月)", "春季银行假日(5月)", "圣诞节(12月25-26日)"],
    trade_notes: [
      "重视传统和礼仪",
      "谈判风格较为间接",
      "决策可能需要时间",
      "下午茶文化仍然重要"
    ],
    driving_side: "left",
    power_plug: "G",
    voltage: "230V"
  }
];

/**
 * 获取国旗的emoji表示
 */
export function getFlagEmoji(countryCode: string): string {
  if (!countryCode || countryCode.length !== 2) return '🌐';
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}

/**
 * 获取指定时区与本地的时差（小时）
 */
export function getTimeDifference(targetTimezone: string): number {
  try {
    const now = new Date();
    const localTimeString = now.toLocaleString('en-US', { timeZone: targetTimezone });
    const targetDate = new Date(localTimeString);
    const diff = now.getTime() - targetDate.getTime();
    return Math.round(diff / (1000 * 60 * 30)) / 2;
  } catch (e) {
    console.error(`Invalid timezone provided: ${targetTimezone}`);
    return 0;
  }
}

/**
 * 获取所有大洲的唯一列表
 */
export const getContinents = () => {
  const continents = new Set(COUNTRY_DATA.map(c => c.continent_cn));
  return Array.from(continents);
};

/**
 * 获取所有货币的唯一列表
 */
export const getCurrencies = () => {
  const currencies = new Map<string, string>();
  COUNTRY_DATA.forEach(country => {
    if (country.currency_code && country.currency_name_cn) {
      currencies.set(country.currency_code, country.currency_name_cn);
    }
  });
  return Array.from(currencies.entries()).map(([code, name]) => ({ code, name }));
};

/**
 * 获取所有语言的唯一列表
 */
export const getLanguages = () => {
  const languages = new Set<string>();
  COUNTRY_DATA.forEach(country => {
    country.language_cn.forEach(lang => languages.add(lang));
  });
  return Array.from(languages).sort();
};

/**
 * 格式化人口数字
 */
export const formatPopulation = (population: number): string => {
  if (population >= 1e9) return `${(population / 1e9).toFixed(1)}B`;
  if (population >= 1e6) return `${(population / 1e6).toFixed(1)}M`;
  if (population >= 1e3) return `${(population / 1e3).toFixed(1)}K`;
  return population.toString();
};

/**
 * 格式化面积
 */
export const formatArea = (area: number): string => {
  return new Intl.NumberFormat('zh-CN').format(area) + ' km²';
};
