// 拼音映射数据库
export const pinyinMap: { [key: string]: string } = {
  // 数字
  '零': 'ling', '一': 'yi', '二': 'er', '三': 'san', '四': 'si', 
  '五': 'wu', '六': 'liu', '七': 'qi', '八': 'ba', '九': 'jiu', 
  '十': 'shi', '百': 'bai', '千': 'qian', '万': 'wan', '亿': 'yi',
  
  // 基础常用字（按使用频率排序）
  '的': 'de', '是': 'shi', '在': 'zai', '有': 'you', '和': 'he',
  '了': 'le', '不': 'bu', '我': 'wo', '你': 'ni', '他': 'ta',
  '她': 'ta', '它': 'ta', '们': 'men', '这': 'zhe', '那': 'na',
  '个': 'ge', '到': 'dao', '大': 'da', '小': 'xiao', '来': 'lai',
  '去': 'qu', '上': 'shang', '下': 'xia', '左': 'zuo', '右': 'you',
  '前': 'qian', '后': 'hou', '里': 'li', '外': 'wai', '多': 'duo',
  '少': 'shao', '好': 'hao', '很': 'hen', '太': 'tai', '都': 'dou',
  
  // 时间相关
  '天': 'tian', '地': 'di', '年': 'nian', '月': 'yue', '日': 'ri',
  '时': 'shi', '分': 'fen', '秒': 'miao', '今': 'jin', '明': 'ming',
  '昨': 'zuo', '春': 'chun', '夏': 'xia', '秋': 'qiu', '冬': 'dong',
  '早': 'zao', '晚': 'wan', '午': 'wu', '晨': 'chen', '夜': 'ye',
  
  // 人物称呼
  '人': 'ren', '民': 'min', '男': 'nan', '女': 'nv', '老': 'lao',
  '少': 'shao', '先': 'xian', '生': 'sheng', '师': 'shi', '友': 'you',
  '父': 'fu', '母': 'mu', '子': 'zi', '儿': 'er', '孩': 'hai',
  '哥': 'ge', '姐': 'jie', '弟': 'di', '妹': 'mei', '夫': 'fu',
  '妻': 'qi', '爸': 'ba', '妈': 'ma', '爷': 'ye', '奶': 'nai',
  
  // 地点方位
  '中': 'zhong', '国': 'guo', '家': 'jia', '北': 'bei', '京': 'jing',
  '东': 'dong', '西': 'xi', '南': 'nan', '海': 'hai', '广': 'guang',
  '州': 'zhou', '深': 'shen', '圳': 'zhen', '香': 'xiang', '港': 'gang',
  '台': 'tai', '湾': 'wan', '市': 'shi', '区': 'qu', '县': 'xian',
  '省': 'sheng', '路': 'lu', '街': 'jie', '道': 'dao', '门': 'men',
  
  // 动作行为
  '说': 'shuo', '话': 'hua', '看': 'kan', '见': 'jian', '听': 'ting',
  '写': 'xie', '读': 'du', '做': 'zuo', '想': 'xiang', '要': 'yao',
  '会': 'hui', '能': 'neng', '可': 'ke', '以': 'yi', '用': 'yong',
  '吃': 'chi', '喝': 'he', '走': 'zou', '跑': 'pao', '飞': 'fei',
  '开': 'kai', '关': 'guan', '打': 'da', '拿': 'na', '给': 'gei',
  
  // 学习工作
  '学': 'xue', '习': 'xi', '校': 'xiao', '课': 'ke', '书': 'shu',
  '本': 'ben', '笔': 'bi', '纸': 'zhi', '工': 'gong', '作': 'zuo',
  '公': 'gong', '司': 'si', '电': 'dian', '脑': 'nao', '手': 'shou',
  '机': 'ji', '话': 'hua', '信': 'xin', '息': 'xi', '网': 'wang',
  
  // 生活物品
  '水': 'shui', '火': 'huo', '饭': 'fan', '菜': 'cai', '茶': 'cha',
  '酒': 'jiu', '肉': 'rou', '鱼': 'yu', '蛋': 'dan', '面': 'mian',
  '包': 'bao', '车': 'che', '房': 'fang', '间': 'jian', '床': 'chuang',
  '桌': 'zhuo', '椅': 'yi', '灯': 'deng', '衣': 'yi', '服': 'fu',
  
  // 自然环境
  '山': 'shan', '河': 'he', '湖': 'hu', '云': 'yun', '雨': 'yu',
  '雪': 'xue', '风': 'feng', '花': 'hua', '草': 'cao', '树': 'shu',
  '林': 'lin', '阳': 'yang', '光': 'guang', '明': 'ming', '亮': 'liang',
  
  // 颜色
  '红': 'hong', '黄': 'huang', '蓝': 'lan', '绿': 'lv', '白': 'bai',
  '黑': 'hei', '灰': 'hui', '色': 'se',
  
  // 数量形容
  '高': 'gao', '低': 'di', '长': 'chang', '短': 'duan', '宽': 'kuan',
  '窄': 'zhai', '厚': 'hou', '薄': 'bao', '重': 'zhong', '轻': 'qing',
  '快': 'kuai', '慢': 'man', '新': 'xin', '旧': 'jiu', '贵': 'gui',
  '便': 'bian', '宜': 'yi', '远': 'yuan', '近': 'jin', '真': 'zhen',
  
  // 情感态度
  '爱': 'ai', '情': 'qing', '心': 'xin', '意': 'yi', '思': 'si',
  '乐': 'le', '喜': 'xi', '欢': 'huan', '怒': 'nu', '哀': 'ai',
  '怕': 'pa', '恨': 'hen', '对': 'dui', '错': 'cuo', '谢': 'xie',
  
  // 常用动词
  '买': 'mai', '卖': 'mai', '找': 'zhao', '到': 'dao', '起': 'qi',
  '出': 'chu', '进': 'jin', '回': 'hui', '过': 'guo', '再': 'zai',
  '还': 'hai', '就': 'jiu', '才': 'cai', '只': 'zhi', '也': 'ye',
  
  // 常用名词
  '事': 'shi', '情': 'qing', '理': 'li', '物': 'wu', '件': 'jian',
  '钱': 'qian', '元': 'yuan', '块': 'kuai', '号': 'hao', '名': 'ming',
  '字': 'zi', '样': 'yang', '点': 'dian', '头': 'tou', '面': 'mian',
  
  // 问候用语
  '您': 'nin', '请': 'qing', '问': 'wen', '什': 'shen', '么': 'me',
  '怎': 'wen', '为': 'wei', '因': 'yin', '所': 'suo', '谁': 'shei',
  '哪': 'na', '吗': 'ma', '呢': 'ne', '吧': 'ba', '啊': 'a',
  
  // 其他常用字
  '着': 'zhe', '被': 'bei', '把': 'ba', '让': 'rang', '叫': 'jiao',
  '像': 'xiang', '如': 'ru', '比': 'bi', '但': 'dan', '而': 'er',
  '或': 'huo', '者': 'zhe', '与': 'yu', '及': 'ji', '等': 'deng',
  '第': 'di', '次': 'ci', '些': 'xie', '每': 'mei', '该': 'gai',
  '当': 'dang', '应': 'ying', '必': 'bi', '须': 'xu', '得': 'de',
  '正': 'zheng', '反': 'fan', '从': 'cong', '向': 'xiang', '往': 'wang',
  '成': 'cheng', '变': 'bian', '化': 'hua', '无': 'wu', '非': 'fei',
  '同': 'tong', '别': 'bie', '种': 'zhong', '各': 'ge', '自': 'zi',
  '己': 'ji', '经': 'jing', '已': 'yi', '将': 'jiang', '此': 'ci',
  '其': 'qi', '实': 'shi', '现': 'xian', '表': 'biao', '里': 'li',
  '定': 'ding', '法': 'fa', '力': 'li', '方': 'fang', '式': 'shi',
  '位': 'wei', '于': 'yu', '之': 'zhi', '内': 'nei', '部': 'bu',
  '份': 'fen', '全': 'quan', '共': 'gong', '总': 'zong', '系': 'xi',
  '列': 'lie', '类': 'lei', '品': 'pin', '质': 'zhi', '性': 'xing',
  '特': 'te', '相': 'xiang', '通': 'tong', '常': 'chang', '直': 'zhi',
  '接': 'jie', '间': 'jian', '题': 'ti', '答': 'da', '案': 'an',
  '结': 'jie', '果': 'guo', '题': 'ti', '目': 'mu', '标': 'biao',
  '准': 'zhun', '确': 'que', '认': 'ren', '知': 'zhi', '识': 'shi',
  '数': 'shu', '量': 'liang', '单': 'dan', '双': 'shuang', '半': 'ban',
  '整': 'zheng', '零': 'ling', '度': 'du', '级': 'ji', '层': 'ceng',
  '界': 'jie', '限': 'xian', '制': 'zhi', '造': 'zao', '产': 'chan',
  '业': 'ye', '展': 'zhan', '发': 'fa', '达': 'da', '步': 'bu',
  '始': 'shi', '终': 'zhong', '期': 'qi', '末': 'mo', '代': 'dai',
  '世': 'shi', '纪': 'ji', '史': 'shi', '古': 'gu', '文': 'wen',
  '言': 'yan', '语': 'yu', '音': 'yin', '声': 'sheng', '调': 'diao',
  '歌': 'ge', '曲': 'qu', '舞': 'wu', '蹈': 'dao', '画': 'hua',
  '图': 'tu', '片': 'pian', '照': 'zhao', '影': 'ying', '视': 'shi',
  '场': 'chang', '景': 'jing', '境': 'jing', '况': 'kuang', '态': 'tai',
  '势': 'shi', '形': 'xing', '状': 'zhuang', '色': 'se', '彩': 'cai',
  '香': 'xiang', '味': 'wei', '道': 'dao', '理': 'li', '由': 'you',
  '原': 'yuan', '则': 'ze', '规': 'gui', '矩': 'ju', '律': 'lv',
  '令': 'ling', '条': 'tiao', '款': 'kuan', '项': 'xiang', '节': 'jie',
  '段': 'duan', '落': 'luo', '句': 'ju', '词': 'ci', '汇': 'hui',
  '典': 'dian', '籍': 'ji', '册': 'ce', '页': 'ye', '张': 'zhang',
  '版': 'ban', '权': 'quan', '利': 'li', '益': 'yi', '处': 'chu',
  '害': 'hai', '损': 'sun', '失': 'shi', '获': 'huo', '胜': 'sheng',
  '败': 'bai', '输': 'shu', '赢': 'ying', '平': 'ping', '局': 'ju',
  '球': 'qiu', '队': 'dui', '员': 'yuan', '长': 'zhang', '官': 'guan',
  '兵': 'bing', '士': 'shi', '民': 'min', '众': 'zhong', '群': 'qun',
  '体': 'ti', '育': 'yu', '运': 'yun', '动': 'dong', '行': 'xing',
  '走': 'zou', '站': 'zhan', '坐': 'zuo', '卧': 'wo', '睡': 'shui',
  '醒': 'xing', '活': 'huo', '死': 'si', '病': 'bing', '医': 'yi',
  '药': 'yao', '院': 'yuan', '店': 'dian', '馆': 'guan', '楼': 'lou',
  '厅': 'ting', '堂': 'tang', '室': 'shi', '厨': 'chu', '厕': 'ce',
  '浴': 'yu', '池': 'chi', '塘': 'tang', '江': 'jiang', '河': 'he',
  '湖': 'hu', '海': 'hai', '洋': 'yang', '洲': 'zhou', '岛': 'dao',
  '屿': 'yu', '岸': 'an', '边': 'bian', '角': 'jiao', '落': 'luo',
  '处': 'chu', '地': 'di', '址': 'zhi', '域': 'yu', '境': 'jing',
  '野': 'ye', '田': 'tian', '土': 'tu', '泥': 'ni', '沙': 'sha',
  '石': 'shi', '岩': 'yan', '矿': 'kuang', '金': 'jin', '银': 'yin',
  '铜': 'tong', '铁': 'tie', '钢': 'gang', '铝': 'lv', '锡': 'xi',
  '木': 'mu', '材': 'cai', '料': 'liao', '布': 'bu', '帛': 'bo',
  '丝': 'si', '绸': 'chou', '缎': 'duan', '棉': 'mian', '麻': 'ma',
  '毛': 'mao', '皮': 'pi', '革': 'ge', '胶': 'jiao', '漆': 'qi',
  '油': 'you', '墨': 'mo', '染': 'ran', '料': 'liao', '剂': 'ji',
  '品': 'pin', '货': 'huo', '商': 'shang', '贸': 'mao', '易': 'yi',
  '交': 'jiao', '换': 'huan', '购': 'gou', '销': 'xiao', '售': 'shou',
  '批': 'pi', '零': 'ling', '价': 'jia', '格': 'ge', '费': 'fei',
  '税': 'shui', '款': 'kuan', '账': 'zhang', '单': 'dan', '据': 'ju',
  '证': 'zheng', '明': 'ming', '书': 'shu', '信': 'xin', '函': 'han',
  '邮': 'you', '寄': 'ji', '送': 'song', '达': 'da', '收': 'shou',
  '取': 'qu', '存': 'cun', '放': 'fang', '置': 'zhi', '摆': 'bai',
  '排': 'pai', '列': 'lie', '序': 'xu', '次': 'ci', '序': 'xu',
  '顺': 'shun', '倒': 'dao', '逆': 'ni', '乱': 'luan', '齐': 'qi',
  '整': 'zheng', '洁': 'jie', '净': 'jing', '脏': 'zang', '污': 'wu',
  '秽': 'hui', '垢': 'gou', '尘': 'chen', '埃': 'ai', '烟': 'yan',
  '雾': 'wu', '霾': 'mai', '霜': 'shuang', '露': 'lu', '霞': 'xia',
  '虹': 'hong', '电': 'dian', '闪': 'shan', '雷': 'lei', '鸣': 'ming',
  '震': 'zhen', '动': 'dong', '摇': 'yao', '晃': 'huang', '颤': 'chan',
  '抖': 'dou', '摆': 'bai', '荡': 'dang', '漾': 'yang', '波': 'bo',
  '涛': 'tao', '浪': 'lang', '潮': 'chao', '汐': 'xi', '流': 'liu',
  '淌': 'tang', '泻': 'xie', '涌': 'yong', '喷': 'pen', '射': 'she',
  '溅': 'jian', '洒': 'sa', '滴': 'di', '漏': 'lou', '渗': 'shen',
  '透': 'tou', '浸': 'jin', '泡': 'pao', '湿': 'shi', '润': 'run',
  '干': 'gan', '燥': 'zao', '枯': 'ku', '萎': 'wei', '谢': 'xie',
  '凋': 'diao', '零': 'ling', '落': 'luo', '飘': 'piao', '散': 'san',
  '聚': 'ju', '集': 'ji', '合': 'he', '并': 'bing', '联': 'lian',
  '结': 'jie', '盟': 'meng', '约': 'yue', '定': 'ding', '立': 'li',
  '建': 'jian', '设': 'she', '施': 'shi', '工': 'gong', '程': 'cheng',
  '筑': 'zhu', '构': 'gou', '架': 'jia', '梁': 'liang', '柱': 'zhu',
  '墙': 'qiang', '壁': 'bi', '顶': 'ding', '底': 'di', '基': 'ji',
  '础': 'chu', '台': 'tai', '阶': 'jie', '梯': 'ti', '扶': 'fu',
  '栏': 'lan', '杆': 'gan', '窗': 'chuang', '户': 'hu', '帘': 'lian',
  '幕': 'mu', '布': 'bu', '挂': 'gua', '钩': 'gou', '钉': 'ding',
  '锤': 'chui', '敲': 'qiao', '击': 'ji', '打': 'da', '砸': 'za',
  '碎': 'sui', '破': 'po', '裂': 'lie', '缝': 'feng', '隙': 'xi',
  '洞': 'dong', '孔': 'kong', '穴': 'xue', '坑': 'keng', '沟': 'gou',
  '渠': 'qu', '管': 'guan', '道': 'dao', '线': 'xian', '路': 'lu',
  '径': 'jing', '途': 'tu', '程': 'cheng', '远': 'yuan', '近': 'jin',
  '遥': 'yao', '迢': 'tiao', '迢': 'tiao', '遥': 'yao', '远': 'yuan',
};
