// 名称: 通用工具注册信息
// 描述: 维护文本、时间、国家、站长、沟通与文件工具元数据
// 路径: Globokit/lib/tools/registry-general.ts
// 作者: everettlabs
// 更新时间: 2026-07-24

import type { ToolMeta } from './registry-types'

export const GENERAL_TOOLS: ToolMeta[] = [
  {
    id: 'text-case',
    slug: 'text-case',
    title: '英文大小写转换',
    shortTitle: '大小写转换',
    description: '快速转换英文文本的大小写格式，支持多种转换模式',
    category: '文本处理',
    iconName: 'Type',
    href: '/tools/text-case',
    updatedAt: '2026-01-13',
    keywords: ['text', 'case', '大小写', '英文', '转换', 'uppercase', 'lowercase'],
    seoTitle: '英文大小写转换 - 在线文本格式转换 | Globokit',
    seoDescription: '免费在线英文大小写转换工具，支持全大写、全小写、首字母大写等多种转换模式',
    useCases: ['邮件标题格式化', '产品名称规范', '代码变量命名'],
    relatedTools: ['pinyin', 'special-char'],
  },
  {
    id: 'pinyin',
    slug: 'pinyin',
    title: '中文转拼音',
    shortTitle: '中文转拼音',
    description: '将中文文本转换为汉语拼音，支持声调和多种格式',
    category: '文本处理',
    iconName: 'Languages',
    href: '/tools/pinyin',
    updatedAt: '2026-01-08',
    keywords: ['pinyin', '拼音', '中文', '汉语', '声调', '转换'],
    seoTitle: '中文转拼音 - 在线汉字拼音转换 | Globokit',
    seoDescription: '免费在线中文转拼音工具，将中文文本转换为汉语拼音，支持声调标注和多种输出格式',
    useCases: ['客户姓名拼音标注', '产品名称国际化', '地址拼音转写'],
    relatedTools: ['text-case', 'special-char'],
  },
  {
    id: 'special-char',
    slug: 'special-char',
    title: '特殊字符检查与转换',
    shortTitle: '特殊字符',
    description: '检查并转换文本中的特殊字符，避免邮件或文档中的乱码',
    category: '文本处理',
    iconName: 'AlertCircle',
    href: '/tools/special-char',
    updatedAt: '2026-01-08',
    keywords: ['special', 'character', '特殊字符', '乱码', '编码', '转换'],
    seoTitle: '特殊字符检查与转换 - 在线字符检测 | Globokit',
    seoDescription: '免费在线特殊字符检查与转换工具，检测并转换文本中的特殊字符，避免邮件或文档乱码',
    useCases: ['邮件内容检查', '文档格式清理', '代码字符排查'],
    relatedTools: ['text-case', 'pinyin'],
  },
  {
    id: 'world-time',
    slug: 'world-time',
    title: '世界时间',
    shortTitle: '世界时间',
    description: '查看全球主要贸易城市和各国首都实时时间，便于安排国际业务',
    category: '时间与节假日',
    iconName: 'Clock',
    href: '/tools/world-time',
    updatedAt: '2026-07-06',
    keywords: ['time', '时间', '时区', '世界', '城市', 'UTC', '时差'],
    seoTitle: '世界时间 - 全球城市实时时钟 | Globokit',
    seoDescription: '免费在线世界时间工具，查看全球主要贸易城市和各国首都实时时间，便于安排国际业务沟通',
    useCases: ['安排国际电话会议', '计算时差', '确认客户工作时间'],
    relatedTools: ['holiday-query', 'delivery-date-calculator', 'global-country-info'],
  },
  {
    id: 'holiday-query',
    slug: 'holiday-query',
    title: '国际节假日查询',
    shortTitle: '节假日查询',
    description: '查询全球国家目录和主要贸易国家节假日安排，便于外贸业务安排',
    category: '时间与节假日',
    iconName: 'Calendar',
    href: '/tools/holiday-query',
    updatedAt: '2026-07-06',
    keywords: ['holiday', '节假日', '假期', '贸易', '国际', '日历'],
    seoTitle: '国际节假日查询 - 全球贸易国节假日 | Globokit',
    seoDescription: '免费在线国际节假日查询工具，查询全球国家目录和主要贸易国家节假日安排，便于外贸业务规划',
    useCases: ['规避节假日发货', '安排拜访客户时间', '制定年度贸易计划'],
    relatedTools: ['delivery-date-calculator', 'world-time', 'global-country-info'],
  },
  {
    id: 'delivery-date-calculator',
    slug: 'delivery-date-calculator',
    title: '外贸交期计算器',
    shortTitle: '交期计算',
    description: '按生产、运输和缓冲周期推算交付日期，支持工作日与国家公共假日口径',
    category: '时间与节假日',
    iconName: 'CalendarClock',
    href: '/tools/delivery-date-calculator',
    updatedAt: '2026-07-24',
    badge: '新增',
    keywords: ['delivery date', '交期', '工作日', '生产周期', '运输周期', '节假日'],
    seoTitle: '外贸交期计算器 - 工作日与节假日交付日期推算 | Globokit',
    seoDescription: '免费在线外贸交期计算器，按生产、运输和缓冲周期推算交付日期，支持自然日、工作日及国家公共假日口径',
    useCases: ['订单交期预估', '生产运输排期', '节假日交付风险核对'],
    relatedTools: ['holiday-query', 'world-time', 'incoterms', 'ocean-freight-calculator', 'demurrage-detention-calculator'],
  },
  {
    id: 'global-country-info',
    slug: 'global-country-info',
    title: '全球国家信息查询',
    shortTitle: '国家信息',
    description: '查询世界各国的中英文名称、区号、代码、时区、域名等信息',
    category: '国家与货币',
    iconName: 'Globe',
    href: '/tools/global-country-info',
    updatedAt: '2026-07-06',
    keywords: ['country', '国家', '区号', '代码', '时区', '域名', 'ISO'],
    seoTitle: '全球国家信息查询 - 各国区号代码时区 | Globokit',
    seoDescription: '免费在线全球国家信息查询，查询世界各国中英文名称、国际区号、ISO代码、时区等信息',
    useCases: ['查询客户国家区号', '确认国家代码', '了解目标市场基本信息'],
    relatedTools: ['world-time', 'holiday-query', 'currency-symbols'],
  },
  {
    id: 'vps-calculator',
    slug: 'vps-calculator',
    title: 'VPS剩余价值计算器',
    shortTitle: 'VPS计算器',
    description: '基于购买日期和到期时间精确计算VPS剩余价值，支持多币种转换',
    category: 'VPS/站长工具',
    iconName: 'Server',
    href: '/tools/vps-calculator',
    updatedAt: '2026-03-16',
    keywords: ['vps', '服务器', '剩余价值', '计算器', '站长', '主机'],
    seoTitle: 'VPS剩余价值计算器 - 精确计算VPS残值 | Globokit',
    seoDescription: '免费在线VPS剩余价值计算器，基于购买日期和到期时间精确计算VPS剩余价值，支持多币种转换',
    useCases: ['VPS转让定价', '续费决策参考', '多台VPS价值对比'],
    relatedTools: [],
  },
  {
    id: 'incoterms',
    slug: 'incoterms',
    title: '国际贸易术语速查',
    shortTitle: '贸易术语',
    description: '快速查询 Incoterms 2020 条款，明确风险转移点与费用责任边界',
    category: '外贸沟通',
    iconName: 'FileSearch',
    href: '/tools/incoterms',
    updatedAt: '2026-06-30',
    badge: '新增',
    keywords: ['incoterms', '贸易术语', 'FOB', 'CIF', 'DDP', 'EXW'],
    seoTitle: '国际贸易术语速查 - Incoterms 2020 在线查询 | Globokit',
    seoDescription: '免费在线 Incoterms 2020 术语速查工具，快速查看 FOB/CIF/DDP 等条款的风险与费用责任划分',
    useCases: ['报价条款确认', '合同条款核对', '新业务员培训'],
    relatedTools: ['container-load-calculator', 'air-freight-calculator', 'ocean-freight-calculator', 'quote-calculator', 'import-landed-cost-calculator', 'holiday-query', 'world-time'],
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    title: 'JSON 格式化与转换',
    shortTitle: 'JSON 工具',
    description: '验证、格式化、压缩 JSON，支持与 CSV 互相转换，便于数据处理',
    category: '文件与格式转换',
    iconName: 'Code2',
    href: '/tools/json-formatter',
    updatedAt: '2026-07-01',
    badge: '新增',
    keywords: ['json', 'format', '格式化', '压缩', 'csv', '转换', '验证'],
    seoTitle: 'JSON 格式化与转换 - 在线 JSON 编辑工具 | Globokit',
    seoDescription: '免费在线 JSON 格式化工具，支持验证、压缩、转换为 CSV 及数据处理，适合开发和数据分析',
    useCases: ['API 数据处理', 'Excel 数据导入', '前端开发调试'],
    relatedTools: ['text-case', 'special-char'],
  },
  {
    id: 'yaml-json-converter',
    slug: 'yaml-json-converter',
    title: 'YAML 与 JSON 互转',
    shortTitle: 'YAML/JSON',
    description: 'YAML 与 JSON 双向转换，支持缩进、引号风格、键排序与往返校验',
    category: '文件与格式转换',
    iconName: 'FileJson',
    href: '/tools/yaml-json-converter',
    updatedAt: '2026-09-18',
    badge: '新增',
    keywords: ['yaml', 'yml', 'json', 'config', 'k8s', 'kubernetes', '配置', '转换', '格式化'],
    seoTitle: 'YAML 与 JSON 互转 - 在线配置文件格式转换 | Globokit',
    seoDescription: '免费在线 YAML 与 JSON 双向转换工具，支持块结构、引号字符串、行尾注释、块标量与键排序，并给出结构统计和往返校验结果',
    useCases: ['K8s 与 Docker Compose 配置转 JSON', '接口返回体转 YAML', '配置文件格式核对与排版'],
    relatedTools: ['json-formatter', 'csv-to-markdown', 'special-char'],
  },
  {
    id: 'csv-to-markdown',
    slug: 'csv-to-markdown',
    title: 'CSV 与 Markdown 表格互转',
    shortTitle: 'CSV/Markdown',
    description: 'CSV 与 Markdown 表格互相转换，支持引号字段与竖线转义',
    category: '文件与格式转换',
    iconName: 'Code2',
    href: '/tools/csv-to-markdown',
    updatedAt: '2026-09-16',
    badge: '新增',
    keywords: ['csv', 'markdown', 'table', '表格', '转换', '导出'],
    seoTitle: 'CSV 与 Markdown 表格互转 - 在线表格格式转换 | Globokit',
    seoDescription: '免费在线 CSV 与 Markdown 表格互转工具，支持带引号的 CSV 字段和竖线转义，适合写文档、贴邮件和交付数据',
    useCases: ['报价表写入文档', 'Markdown 表格回填 Excel', '整理客户数据'],
    relatedTools: ['json-formatter', 'supplier-quote-comparison'],
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp-converter',
    title: 'Unix 时间戳转换',
    shortTitle: '时间戳转换',
    description: 'Unix 时间戳与北京时间日期互转，支持秒/毫秒口径与实时时间戳',
    category: 'VPS/站长工具',
    iconName: 'Clock',
    href: '/tools/timestamp-converter',
    updatedAt: '2026-09-16',
    badge: '新增',
    keywords: ['timestamp', 'unix', '时间戳', 'epoch', '日期', '转换'],
    seoTitle: 'Unix 时间戳转换 - 时间戳与北京时间互转 | Globokit',
    seoDescription: '免费在线 Unix 时间戳转换工具，时间戳与北京时间日期互转，支持秒/毫秒口径和实时时间戳复制',
    useCases: ['排查服务器日志', '核对回调参数时间', 'API 数据调试'],
    relatedTools: ['world-time', 'delivery-date-calculator', 'vps-calculator'],
  },
  {
    id: 'email-phrase-library',
    slug: 'email-phrase-library',
    title: '外贸邮件话术库',
    shortTitle: '邮件话术',
    description: '按开发、报价、订单、收款与售后场景检索常用外贸英文邮件话术',
    category: '外贸沟通',
    iconName: 'MailCheck',
    href: '/tools/email-phrase-library',
    updatedAt: '2026-09-16',
    badge: '新增',
    keywords: ['email', '邮件', '话术', '模板', '开发信', '跟进', '催款'],
    seoTitle: '外贸邮件话术库 - 英文邮件模板速查 | Globokit',
    seoDescription: '免费外贸英文邮件话术库，覆盖客户开发、报价议价、订单生产、收款发货与售后场景，一键复制模板',
    useCases: ['撰写开发信', '跟进催款', '回复客户投诉'],
    relatedTools: ['incoterms', 'text-case', 'special-char', 'world-time'],
  },
  {
    id: 'voltage-plug-guide',
    slug: 'voltage-plug-guide',
    title: '目标市场电压与插头速查',
    shortTitle: '电压插头',
    description: '查询主要贸易国家的市电电压、频率与插头类型，确认产品适配方案',
    category: '国家与货币',
    iconName: 'Zap',
    href: '/tools/voltage-plug-guide',
    updatedAt: '2026-09-16',
    badge: '新增',
    keywords: ['voltage', 'plug', '电压', '插头', '频率', '出口', '认证'],
    seoTitle: '目标市场电压与插头速查 - 各国市电规格查询 | Globokit',
    seoDescription: '免费在线各国电压与插头类型速查工具，覆盖主要贸易市场的市电电压、频率和插头标准，辅助电子产品出货适配',
    useCases: ['电器产品适配确认', '随机插头出货方案', '客户技术问答'],
    relatedTools: ['global-country-info', 'incoterms', 'import-landed-cost-calculator'],
  },
  {
    id: 'remittance-cost-calculator',
    slug: 'remittance-cost-calculator',
    title: '国际收款渠道费用对比',
    shortTitle: '收款渠道对比',
    description: '比较电汇、信用证、托收与第三方渠道的手续费、汇损与资金占用，算出实际到手金额',
    category: '国家与货币',
    iconName: 'Wallet',
    href: '/tools/remittance-cost-calculator',
    updatedAt: '2026-09-18',
    badge: '新增',
    keywords: ['remittance', 'tt', 'lc', '收款', '电汇', '信用证', '手续费', '汇款', '汇率'],
    seoTitle: '国际收款渠道费用对比 - 电汇信用证手续费测算 | Globokit',
    seoDescription: '免费在线国际收款渠道对比工具，按订单金额与汇率折算，比较电汇、信用证、托收与第三方渠道的手续费、汇损、资金占用与到手金额',
    useCases: ['报价前核算收款成本', '选择信用证还是电汇', '小额订单渠道选择'],
    relatedTools: ['fx-sensitivity-calculator', 'payment-terms-calculator', 'currency-symbols'],
  },
  {
    id: 'inquiry-priority-scorer',
    slug: 'inquiry-priority-scorer',
    title: '外贸询盘优先级评估',
    shortTitle: '询盘优先级',
    description: '按询盘完整度、客户可信度与商务价值打分，输出优先级、回应时限与追问话术',
    category: '外贸沟通',
    iconName: 'Gauge',
    href: '/tools/inquiry-priority-scorer',
    updatedAt: '2026-09-18',
    badge: '新增',
    keywords: ['inquiry', '询盘', '优先级', '客户开发', '跟进', '话术', '邮件'],
    seoTitle: '外贸询盘优先级评估 - 询盘打分与跟进话术 | Globokit',
    seoDescription: '免费在线外贸询盘优先级评估工具，按信息完整度、客户可信度与商务价值打分，给出回应时限、缺失信息清单与中英文追问话术',
    useCases: ['判断先回哪封询盘', '生成追问邮件话术', '新业务回复节奏规范'],
    relatedTools: ['email-phrase-library', 'delivery-date-calculator', 'quote-calculator'],
  },
  {
    id: 'server-cost-comparison',
    slug: 'server-cost-comparison',
    title: '服务器成本对比',
    shortTitle: '服务器成本',
    description: '比较 2–5 台服务器的套餐价、续费价与附加成本，输出月均、持有期总成本与单位算力性价比',
    category: 'VPS/站长工具',
    iconName: 'Server',
    href: '/tools/server-cost-comparison',
    updatedAt: '2026-09-18',
    badge: '新增',
    keywords: ['vps', 'server', '服务器', '成本', '续费', '性价比', '月均成本', '主机'],
    seoTitle: '服务器成本对比 - 月均成本与续费价测算 | Globokit',
    seoDescription: '免费在线服务器成本对比工具，同时比较多台 VPS 或独立服务器的套餐价、续费价、附加费与首期优惠，输出月均成本、三年持有成本与单位算力性价比',
    useCases: ['活动机与月付机取舍', '续费涨价前的成本复核', '多机房预算横向比较'],
    relatedTools: ['vps-calculator', 'world-time', 'express-channel-comparison'],
  },
]
