// 名称: 物流与装柜工具注册信息
// 描述: 集中维护物流与装柜分类的工具元数据
// 路径: Globokit/lib/tools/registry-logistics.ts
// 作者: everettlabs
// 更新时间: 2026-07-15

import type { ToolMeta } from './registry-types'

export const LOGISTICS_TOOLS: ToolMeta[] = [
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    title: '外贸单位换算器',
    shortTitle: '单位换算',
    description: '换算物流与产品规格常用的公制、英制长度、重量和体积单位',
    category: '物流与装柜',
    iconName: 'Ruler',
    href: '/tools/unit-converter',
    updatedAt: '2026-07-21',
    badge: '新增',
    keywords: ['unit converter', '单位换算', '长度', '重量', '体积', 'CBM', '英寸', '磅'],
    seoTitle: '外贸单位换算器 - 长度重量体积在线换算 | Globokit',
    seoDescription: '免费在线外贸单位换算器，支持物流和产品规格常用的公制与英制长度、重量、体积单位换算',
    useCases: ['产品尺寸单位换算', '装箱重量换算', 'CBM 与立方英尺换算'],
    relatedTools: ['container-load-calculator', 'pallet-load-calculator', 'air-freight-calculator', 'ocean-freight-calculator'],
  },
  {
    id: 'container-load-calculator',
    slug: 'container-load-calculator',
    title: '装柜/箱规计算器',
    shortTitle: '装柜计算',
    description: '按纸箱尺寸、毛重、数量和柜型估算整柜装载数量、柜数与利用率',
    category: '物流与装柜',
    iconName: 'Container',
    href: '/tools/container-load-calculator',
    updatedAt: '2026-07-06',
    badge: '新增',
    keywords: ['container', '装柜', '箱规', 'CBM', '柜型', '物流', '20GP', '40HQ'],
    seoTitle: '装柜/箱规计算器 - 纸箱 CBM 与整柜装载估算 | Globokit',
    seoDescription: '免费在线装柜/箱规计算器，按纸箱尺寸、毛重、箱数和 20GP/40GP/40HQ/45HQ 柜型估算装载数量、柜数和利用率',
    useCases: ['报价前估算装柜量', '核对纸箱 CBM', '评估整柜数量和载重限制'],
    relatedTools: ['pallet-load-calculator', 'quote-calculator', 'air-freight-calculator', 'ocean-freight-calculator', 'incoterms', 'currency-symbols'],
  },
  {
    id: 'pallet-load-calculator',
    slug: 'pallet-load-calculator',
    title: '托盘装载计算器',
    shortTitle: '托盘装载',
    description: '按纸箱、托盘规格、高度和载重限制估算每层箱数、单托装载量与所需托盘数',
    category: '物流与装柜',
    iconName: 'Pallet',
    href: '/tools/pallet-load-calculator',
    updatedAt: '2026-07-12',
    badge: '新增',
    keywords: ['pallet', '托盘', '栈板', '码托', '装载', '纸箱', '欧标托盘'],
    seoTitle: '托盘装载计算器 - 纸箱码托与托盘数量估算 | Globokit',
    seoDescription: '免费在线托盘装载计算器，按纸箱尺寸、重量、托盘规格、限高和限重估算每层箱数、码放层数、单托装载量及所需托盘数',
    useCases: ['出货前估算码托数量', '核对单托高度与毛重', '比较中欧及北美托盘装载量'],
    relatedTools: ['container-load-calculator', 'air-freight-calculator', 'ocean-freight-calculator', 'express-channel-comparison'],
  },
  {
    id: 'air-freight-calculator',
    slug: 'air-freight-calculator',
    title: '空运/快递计费重计算器',
    shortTitle: '空运计费重',
    description: '按箱规、实重、泡重系数和运价测算空运快递计费重量与费用',
    category: '物流与装柜',
    iconName: 'Plane',
    href: '/tools/air-freight-calculator',
    updatedAt: '2026-07-07',
    badge: '新增',
    keywords: ['air freight', 'express', '空运', '快递', '计费重', '泡重', '体积重', 'DHL', 'FedEx', 'UPS'],
    seoTitle: '空运/快递计费重计算器 - 泡重体积重费用测算 | Globokit',
    seoDescription: '免费在线空运/快递计费重计算器，按纸箱尺寸、实重、泡重系数、每公斤运价、燃油附加和操作费估算计费重量与费用',
    useCases: ['空运快递报价核算', '判断实重或体积重计费', '比较不同泡重系数费用'],
    relatedTools: ['container-load-calculator', 'express-channel-comparison', 'ocean-freight-calculator', 'quote-calculator', 'incoterms', 'currency-symbols'],
  },
  {
    id: 'ocean-freight-calculator',
    slug: 'ocean-freight-calculator',
    title: '海运费用拆分计算器',
    shortTitle: '海运费用',
    description: '汇总海运费、港杂、拖车、报关、保险和目的港费用，测算每件与每CBM成本',
    category: '物流与装柜',
    iconName: 'Ship',
    href: '/tools/ocean-freight-calculator',
    updatedAt: '2026-07-08',
    badge: '新增',
    keywords: ['ocean freight', 'sea freight', '海运', '港杂', '报关', '保险', 'FCL', 'LCL', 'CBM'],
    seoTitle: '海运费用拆分计算器 - FCL/LCL 每件每CBM成本测算 | Globokit',
    seoDescription: '免费在线海运费用拆分计算器，按海运费、起运港杂费、拖车、报关、保险和目的港费用测算 FCL/LCL 每件与每CBM成本',
    useCases: ['海运报价前成本拆分', '整柜和拼箱费用摊销', '核算每件与每CBM物流成本'],
    relatedTools: ['container-load-calculator', 'air-freight-calculator', 'customs-cost-calculator', 'quote-calculator', 'import-landed-cost-calculator', 'incoterms'],
  },
  {
    id: 'customs-cost-calculator',
    slug: 'customs-cost-calculator',
    title: '报关费用估算器',
    shortTitle: '报关费用',
    description: '汇总报关、单证、代理、查验和本地操作费用，测算每票与每件成本',
    category: '物流与装柜',
    iconName: 'FileCheck2',
    href: '/tools/customs-cost-calculator',
    updatedAt: '2026-07-11',
    badge: '新增',
    keywords: ['customs', '报关', '清关', '查验', '单证', '代理费', '出口', '进口'],
    seoTitle: '报关费用估算器 - 出口报关与进口清关成本测算 | Globokit',
    seoDescription: '免费在线报关费用估算器，汇总报关、单证、代理、查验、港区操作和国内运输费用，测算每票与每件成本',
    useCases: ['出口报价前报关预算', '进口清关费用预估', '多票货物费用摊销'],
    relatedTools: ['express-channel-comparison', 'import-landed-cost-calculator', 'ocean-freight-calculator', 'quote-calculator', 'incoterms'],
  },
  {
    id: 'express-channel-comparison',
    slug: 'express-channel-comparison',
    title: '快递渠道价格对比',
    shortTitle: '快递比价',
    description: '统一燃油、偏远、报关等附加费口径，对比快递渠道真实成本与时效',
    category: '物流与装柜',
    iconName: 'GitCompareArrows',
    href: '/tools/express-channel-comparison',
    updatedAt: '2026-07-11',
    badge: '新增',
    keywords: ['express', '快递', '渠道', '比价', '燃油附加', '偏远费', '时效'],
    seoTitle: '快递渠道价格对比 - 运费附加费与时效比较 | Globokit',
    seoDescription: '免费在线快递渠道价格对比工具，统一计算基础运费、燃油、偏远、报关和其他附加费，对比每公斤成本与运输时效',
    useCases: ['国际快递渠道比价', '货代报价成本核对', '成本与时效方案选择'],
    relatedTools: ['air-freight-calculator', 'customs-cost-calculator', 'quote-calculator', 'container-load-calculator'],
  },
]
