// 名称: 通用工具注册信息
// 描述: 维护文本、时间、国家、站长、沟通与文件工具元数据
// 路径: Globokit/lib/tools/registry-general.ts
// 作者: everettlabs
// 更新时间: 2026-07-15

import type { ToolMeta } from './registry-types'

export const GENERAL_TOOLS: ToolMeta[] = [
  {
    id: 'text-case',
    slug: 'text-case',
    title: '英文大小写转换',
    shortTitle: '大小写转换',
    description: '快速转换英文文本的大小写格式，支持多种转换模式',
    category: '文本处理',
    iconName: 'Type',
    href: '/tools/text-case',
    updatedAt: '2026-01-13',
    keywords: ['text', 'case', '大小写', '英文', '转换', 'uppercase', 'lowercase'],
    seoTitle: '英文大小写转换 - 在线文本格式转换 | Globokit',
    seoDescription: '免费在线英文大小写转换工具，支持全大写、全小写、首字母大写等多种转换模式',
    useCases: ['邮件标题格式化', '产品名称规范', '代码变量命名'],
    relatedTools: ['pinyin', 'special-char'],
  },
  {
    id: 'pinyin',
    slug: 'pinyin',
    title: '中文转拼音',
    shortTitle: '中文转拼音',
    description: '将中文文本转换为汉语拼音，支持声调和多种格式',
    category: '文本处理',
    iconName: 'Languages',
    href: '/tools/pinyin',
    updatedAt: '2026-01-08',
    keywords: ['pinyin', '拼音', '中文', '汉语', '声调', '转换'],
    seoTitle: '中文转拼音 - 在线汉字拼音转换 | Globokit',
    seoDescription: '免费在线中文转拼音工具，将中文文本转换为汉语拼音，支持声调标注和多种输出格式',
    useCases: ['客户姓名拼音标注', '产品名称国际化', '地址拼音转写'],
    relatedTools: ['text-case', 'special-char'],
  },
  {
    id: 'special-char',
    slug: 'special-char',
    title: '特殊字符检查与转换',
    shortTitle: '特殊字符',
    description: '检查并转换文本中的特殊字符，避免邮件或文档中的乱码',
    category: '文本处理',
    iconName: 'AlertCircle',
    href: '/tools/special-char',
    updatedAt: '2026-01-08',
    keywords: ['special', 'character', '特殊字符', '乱码', '编码', '转换'],
    seoTitle: '特殊字符检查与转换 - 在线字符检测 | Globokit',
    seoDescription: '免费在线特殊字符检查与转换工具，检测并转换文本中的特殊字符，避免邮件或文档乱码',
    useCases: ['邮件内容检查', '文档格式清理', '代码字符排查'],
    relatedTools: ['text-case', 'pinyin'],
  },
  {
    id: 'world-time',
    slug: 'world-time',
    title: '世界时间',
    shortTitle: '世界时间',
    description: '查看全球主要贸易城市和各国首都实时时间，便于安排国际业务',
    category: '时间与节假日',
    iconName: 'Clock',
    href: '/tools/world-time',
    updatedAt: '2026-07-06',
    keywords: ['time', '时间', '时区', '世界', '城市', 'UTC', '时差'],
    seoTitle: '世界时间 - 全球城市实时时钟 | Globokit',
    seoDescription: '免费在线世界时间工具，查看全球主要贸易城市和各国首都实时时间，便于安排国际业务沟通',
    useCases: ['安排国际电话会议', '计算时差', '确认客户工作时间'],
    relatedTools: ['holiday-query', 'delivery-date-calculator', 'global-country-info'],
  },
  {
    id: 'holiday-query',
    slug: 'holiday-query',
    title: '国际节假日查询',
    shortTitle: '节假日查询',
    description: '查询全球国家目录和主要贸易国家节假日安排，便于外贸业务安排',
    category: '时间与节假日',
    iconName: 'Calendar',
    href: '/tools/holiday-query',
    updatedAt: '2026-07-06',
    keywords: ['holiday', '节假日', '假期', '贸易', '国际', '日历'],
    seoTitle: '国际节假日查询 - 全球贸易国节假日 | Globokit',
    seoDescription: '免费在线国际节假日查询工具，查询全球国家目录和主要贸易国家节假日安排，便于外贸业务规划',
    useCases: ['规避节假日发货', '安排拜访客户时间', '制定年度贸易计划'],
    relatedTools: ['delivery-date-calculator', 'world-time', 'global-country-info'],
  },
  {
    id: 'delivery-date-calculator',
    slug: 'delivery-date-calculator',
    title: '外贸交期计算器',
    shortTitle: '交期计算',
    description: '按生产、运输和缓冲周期推算交付日期，支持工作日与国家公共假日口径',
    category: '时间与节假日',
    iconName: 'CalendarClock',
    href: '/tools/delivery-date-calculator',
    updatedAt: '2026-07-21',
    badge: '新增',
    keywords: ['delivery date', '交期', '工作日', '生产周期', '运输周期', '节假日'],
    seoTitle: '外贸交期计算器 - 工作日与节假日交付日期推算 | Globokit',
    seoDescription: '免费在线外贸交期计算器，按生产、运输和缓冲周期推算交付日期，支持自然日、工作日及国家公共假日口径',
    useCases: ['订单交期预估', '生产运输排期', '节假日交付风险核对'],
    relatedTools: ['holiday-query', 'world-time', 'incoterms', 'ocean-freight-calculator'],
  },
  {
    id: 'global-country-info',
    slug: 'global-country-info',
    title: '全球国家信息查询',
    shortTitle: '国家信息',
    description: '查询世界各国的中英文名称、区号、代码、时区、域名等信息',
    category: '国家与货币',
    iconName: 'Globe',
    href: '/tools/global-country-info',
    updatedAt: '2026-07-06',
    keywords: ['country', '国家', '区号', '代码', '时区', '域名', 'ISO'],
    seoTitle: '全球国家信息查询 - 各国区号代码时区 | Globokit',
    seoDescription: '免费在线全球国家信息查询，查询世界各国中英文名称、国际区号、ISO代码、时区等信息',
    useCases: ['查询客户国家区号', '确认国家代码', '了解目标市场基本信息'],
    relatedTools: ['world-time', 'holiday-query', 'currency-symbols'],
  },
  {
    id: 'vps-calculator',
    slug: 'vps-calculator',
    title: 'VPS剩余价值计算器',
    shortTitle: 'VPS计算器',
    description: '基于购买日期和到期时间精确计算VPS剩余价值，支持多币种转换',
    category: 'VPS/站长工具',
    iconName: 'Server',
    href: '/tools/vps-calculator',
    updatedAt: '2026-03-16',
    keywords: ['vps', '服务器', '剩余价值', '计算器', '站长', '主机'],
    seoTitle: 'VPS剩余价值计算器 - 精确计算VPS残值 | Globokit',
    seoDescription: '免费在线VPS剩余价值计算器，基于购买日期和到期时间精确计算VPS剩余价值，支持多币种转换',
    useCases: ['VPS转让定价', '续费决策参考', '多台VPS价值对比'],
    relatedTools: [],
  },
  {
    id: 'incoterms',
    slug: 'incoterms',
    title: '国际贸易术语速查',
    shortTitle: '贸易术语',
    description: '快速查询 Incoterms 2020 条款，明确风险转移点与费用责任边界',
    category: '外贸沟通',
    iconName: 'FileSearch',
    href: '/tools/incoterms',
    updatedAt: '2026-06-30',
    badge: '新增',
    keywords: ['incoterms', '贸易术语', 'FOB', 'CIF', 'DDP', 'EXW'],
    seoTitle: '国际贸易术语速查 - Incoterms 2020 在线查询 | Globokit',
    seoDescription: '免费在线 Incoterms 2020 术语速查工具，快速查看 FOB/CIF/DDP 等条款的风险与费用责任划分',
    useCases: ['报价条款确认', '合同条款核对', '新业务员培训'],
    relatedTools: ['container-load-calculator', 'air-freight-calculator', 'ocean-freight-calculator', 'quote-calculator', 'import-landed-cost-calculator', 'holiday-query', 'world-time'],
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    title: 'JSON 格式化与转换',
    shortTitle: 'JSON 工具',
    description: '验证、格式化、压缩 JSON，支持与 CSV 互相转换，便于数据处理',
    category: '文件与格式转换',
    iconName: 'Code2',
    href: '/tools/json-formatter',
    updatedAt: '2026-07-01',
    badge: '新增',
    keywords: ['json', 'format', '格式化', '压缩', 'csv', '转换', '验证'],
    seoTitle: 'JSON 格式化与转换 - 在线 JSON 编辑工具 | Globokit',
    seoDescription: '免费在线 JSON 格式化工具，支持验证、压缩、转换为 CSV 及数据处理，适合开发和数据分析',
    useCases: ['API 数据处理', 'Excel 数据导入', '前端开发调试'],
    relatedTools: ['text-case', 'special-char'],
  },
]
