// 名称: 财务报价工具注册信息
// 描述: 集中维护财务报价分类的工具元数据
// 路径: Globokit/lib/tools/registry-finance.ts
// 作者: everettlabs
// 更新时间: 2026-08-11

import type { ToolMeta } from './registry-types'

export const FINANCE_TOOLS: ToolMeta[] = [
  {
    id: 'rmb-converter',
    slug: 'rmb-converter',
    title: '人民币大写转换',
    shortTitle: '人民币大写',
    description: '将数字金额转换为中文大写形式，适用于发票、合同等正式文件',
    category: '财务报价',
    iconName: 'Calculator',
    href: '/tools/rmb-converter',
    updatedAt: '2026-01-08',
    badge: '热门',
    keywords: ['rmb', '人民币', '大写', '金额', '发票', '合同'],
    seoTitle: '人民币大写转换 - 在线数字转中文大写 | Globokit',
    seoDescription: '免费在线人民币大写转换工具，将数字金额转换为中文大写形式，适用于发票合同等正式文件',
    useCases: ['开具发票', '填写合同', '财务报销单'],
    relatedTools: ['number-to-english', 'currency-symbols', 'quote-calculator'],
  },
  {
    id: 'number-to-english',
    slug: 'number-to-english',
    title: '数字转英文',
    shortTitle: '数字转英文',
    description: '将数字转换为英文表达形式，支持基数词和序数词',
    category: '财务报价',
    iconName: 'Hash',
    href: '/tools/number-to-english',
    updatedAt: '2026-01-08',
    keywords: ['number', 'english', '数字', '英文', '基数词', '序数词'],
    seoTitle: '数字转英文 - 在线数字英文转换 | Globokit',
    seoDescription: '免费在线数字转英文工具，将数字转换为英文表达形式，支持基数词和序数词转换',
    useCases: ['外贸合同金额', '英文支票填写', '商务邮件数字表达'],
    relatedTools: ['rmb-converter', 'currency-symbols'],
  },
  {
    id: 'currency-symbols',
    slug: 'currency-symbols',
    title: '全球货币符号大全',
    shortTitle: '货币符号',
    description: '查看和复制全球货币符号，覆盖国家资料库中的常用和长尾货币',
    category: '财务报价',
    iconName: 'CircleDollarSign',
    href: '/tools/currency-symbols',
    updatedAt: '2026-07-06',
    keywords: ['currency', '货币', '符号', '外贸', '报价', '汇率'],
    seoTitle: '全球货币符号大全 - 一键复制货币符号 | Globokit',
    seoDescription: '查看和复制全球货币符号，涵盖主要贸易国家和长尾国家货币，便于外贸报价和合同编写',
    useCases: ['外贸报价单', '合同编写', '邮件中引用货币'],
    relatedTools: ['rmb-converter', 'number-to-english', 'global-country-info', 'quote-calculator', 'fx-sensitivity-calculator', 'import-landed-cost-calculator'],
  },
  {
    id: 'quote-calculator',
    slug: 'quote-calculator',
    title: '外贸报价利润计算器',
    shortTitle: '报价利润',
    description: '按 EXW/FCA/FOB/CIF/DDP 等条款、成本、运费和利润率测算外贸报价',
    category: '财务报价',
    iconName: 'ReceiptText',
    href: '/tools/quote-calculator',
    updatedAt: '2026-07-08',
    badge: '新增',
    keywords: ['quote', 'quotation', '报价', '利润', 'EXW', 'FCA', 'FOB', 'CFR', 'CIF', 'CPT', 'CIP', 'DAP', 'DDP', '汇率', '外贸'],
    seoTitle: '外贸报价利润计算器 - EXW/FOB/CIF/DDP 条款报价测算 | Globokit',
    seoDescription: '免费在线外贸报价利润计算器，支持 EXW、FCA、FOB、CFR、CIF、CPT、CIP、DAP、DDP 等条款，按采购成本、运费、保险、税费、佣金和目标利润率测算报价',
    useCases: ['外贸报价核算', 'Incoterms 条款报价', '含运费含税报价评估'],
    relatedTools: ['tiered-quote-calculator', 'order-break-even-calculator', 'payment-terms-calculator', 'fx-sensitivity-calculator', 'export-tax-rebate-calculator', 'currency-symbols', 'import-landed-cost-calculator', 'container-load-calculator', 'air-freight-calculator', 'ocean-freight-calculator', 'incoterms'],
  },
  {
    id: 'tiered-quote-calculator',
    slug: 'tiered-quote-calculator',
    title: '外贸阶梯报价计算器',
    shortTitle: '阶梯报价',
    description: '按订购数量、采购单价、固定费用和目标利润率反算外币阶梯报价',
    category: '财务报价',
    iconName: 'ListOrdered',
    href: '/tools/tiered-quote-calculator',
    updatedAt: '2026-08-11',
    badge: '新增',
    keywords: ['tiered quote', '阶梯报价', '数量折扣', '批量报价', 'MOQ', '采购成本', '利润率', '外贸'],
    seoTitle: '外贸阶梯报价计算器 - 数量折扣与批量单价测算 | Globokit',
    seoDescription: '免费在线外贸阶梯报价计算器，按不同订购数量与采购单价摊薄固定费用，结合佣金、收款费、汇率和目标利润率生成外币阶梯单价',
    useCases: ['客户询盘阶梯报价', 'MOQ 与批量折扣设计', '采购成本降幅测算'],
    relatedTools: ['order-break-even-calculator', 'quote-calculator', 'payment-terms-calculator', 'fx-sensitivity-calculator', 'export-tax-rebate-calculator', 'currency-symbols', 'container-load-calculator'],
  },
  {
    id: 'order-break-even-calculator',
    slug: 'order-break-even-calculator',
    title: '外贸订单保本销量计算器',
    shortTitle: '订单保本销量',
    description: '按售价、变动成本、固定成本和成交费率测算保本与目标利润销量',
    category: '财务报价',
    iconName: 'ShieldCheck',
    href: '/tools/order-break-even-calculator',
    updatedAt: '2026-08-11',
    badge: '新增',
    keywords: ['break even', '保本销量', '盈亏平衡', '贡献毛利', '目标利润', '固定成本', '外贸订单'],
    seoTitle: '外贸订单保本销量计算器 - 盈亏平衡与目标利润销量 | Globokit',
    seoDescription: '免费在线外贸订单保本销量计算器，按销售单价、单件变动成本、固定成本、佣金、收款费和售后损耗测算保本销量、目标利润销量与计划订单利润',
    useCases: ['外贸订单最低销量评估', '已知售价盈亏平衡测算', '目标利润数量谈判'],
    relatedTools: ['quote-calculator', 'tiered-quote-calculator', 'payment-terms-calculator', 'fx-sensitivity-calculator', 'export-tax-rebate-calculator'],
  },
  {
    id: 'payment-terms-calculator',
    slug: 'payment-terms-calculator',
    title: '外贸收款账期成本对比',
    shortTitle: '收款账期成本',
    description: '比较 T/T、L/C、D/P 与 OA 的资金占用、收款费用、风险准备金和实际利润',
    category: '财务报价',
    iconName: 'Landmark',
    href: '/tools/payment-terms-calculator',
    updatedAt: '2026-08-10',
    badge: '新增',
    keywords: ['payment terms', 'T/T', 'L/C', 'D/P', 'OA', '账期', '收款', '资金成本', '外贸'],
    seoTitle: '外贸收款账期成本对比 - T/T、L/C、D/P、OA 利润测算 | Globokit',
    seoDescription: '免费比较 T/T、L/C、D/P 与 OA 收款条件，估算资金占用、银行手续费、风险准备金、回款周期和订单实际利润',
    useCases: ['客户付款条件谈判', '账期资金成本测算', 'T/T 与 L/C 方案对比'],
    relatedTools: ['order-break-even-calculator', 'tiered-quote-calculator', 'quote-calculator', 'fx-sensitivity-calculator', 'export-tax-rebate-calculator', 'currency-symbols', 'delivery-date-calculator'],
  },
  {
    id: 'fx-sensitivity-calculator',
    slug: 'fx-sensitivity-calculator',
    title: '外贸汇率敏感性分析',
    shortTitle: '汇率敏感性',
    description: '比较人民币升值、基准和贬值情景下外币订单的收入、利润与盈亏平衡汇率',
    category: '财务报价',
    iconName: 'TrendingUp',
    href: '/tools/fx-sensitivity-calculator',
    updatedAt: '2026-08-11',
    badge: '新增',
    keywords: ['FX', 'exchange rate', '汇率', '汇兑', '利润敏感性', '盈亏平衡', '外贸报价'],
    seoTitle: '外贸汇率敏感性分析 - 汇率波动与订单利润测算 | Globokit',
    seoDescription: '免费在线外贸汇率敏感性分析工具，比较人民币升值、基准和贬值情景下的 CNY 收入、收款手续费、订单利润与盈亏平衡汇率',
    useCases: ['外币订单利润预算', '报价汇率风险评估', '结汇谈判与汇兑损益测算'],
    relatedTools: ['tiered-quote-calculator', 'quote-calculator', 'payment-terms-calculator', 'export-tax-rebate-calculator', 'currency-symbols'],
  },
  {
    id: 'export-tax-rebate-calculator',
    slug: 'export-tax-rebate-calculator',
    title: '出口退税计算器',
    shortTitle: '出口退税',
    description: '按采购发票、增值税率、退税率和 FOB 收入估算退税额与退税后利润',
    category: '财务报价',
    iconName: 'HandCoins',
    href: '/tools/export-tax-rebate-calculator',
    updatedAt: '2026-07-24',
    badge: '新增',
    keywords: ['export tax rebate', '出口', '退税', '增值税', 'FOB', '利润', '进项税'],
    seoTitle: '出口退税计算器 - 退税额与出口利润测算 | Globokit',
    seoDescription: '免费在线出口退税计算器，支持含税与未税采购口径，按增值税率、退税率、FOB 收入和出口费用估算退税额与利润',
    useCases: ['出口订单利润核算', '采购发票税额拆分', '征退税差成本评估'],
    relatedTools: ['quote-calculator', 'customs-cost-calculator', 'currency-symbols', 'incoterms'],
  },
  {
    id: 'import-landed-cost-calculator',
    slug: 'import-landed-cost-calculator',
    title: '进口到岸成本计算器',
    shortTitle: '到岸成本',
    description: '按货值、运费、保险、关税、增值税和本地费用测算进口到岸成本',
    category: '财务报价',
    iconName: 'ReceiptText',
    href: '/tools/import-landed-cost-calculator',
    updatedAt: '2026-07-08',
    badge: '新增',
    keywords: ['landed cost', '进口', '到岸成本', '关税', '增值税', 'CIF', '税费', '清关'],
    seoTitle: '进口到岸成本计算器 - 关税增值税与每件成本测算 | Globokit',
    seoDescription: '免费在线进口到岸成本计算器，按货值、运费、保险、关税、增值税、清关和本地费用测算总成本与每件成本',
    useCases: ['进口报价前成本核算', '关税增值税预算', '销售单价毛利评估'],
    relatedTools: ['quote-calculator', 'currency-symbols', 'customs-cost-calculator', 'ocean-freight-calculator', 'air-freight-calculator', 'incoterms'],
  },
]
